// build.ts writes ../server-manifest.ts; this types its import before the first build.
/// <reference types="@nifrajs/web/server-manifest" />
import { inProcessClient } from "@nifrajs/client"
import { createWebApp } from "@nifrajs/web"
import { reactAdapter } from "@nifrajs/web-react"
// Generated by build.ts (buildServer) - the static-import route manifest + baked client entry URL.
import { clientEntry, manifest } from "../server-manifest"
import { backend } from "./app"

/** The nifra app - identical across every runtime. Only the entry that wraps it differs. */
export const app = createWebApp({
  adapter: reactAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra - portable SSR",
})
