/**
 * Type-level SCALING regression for the route registry.
 *
 * Measured ceiling: a single fluent chain accumulates one alias level per route and TypeScript
 * resolves the stack in one recursion — TS2589 fires at ~95-100 chained calls. This file pins
 * BOTH sides of that contract:
 *   1. a 90-route single chain stays clean (headroom below the ceiling must not regress), and
 *   2. 120 routes composed from 4 merged 30-route groups typecheck with full fidelity
 *      (merge() is the supported way past the ceiling; contract-first implement() is the other).
 * If this file starts erroring, AddRoute (or the compiler) changed shape — see registry.ts.
 */
import { server } from "../src/index.ts"

// ── 1. single chain at 90: inside the supported ceiling ──────────────────────────────────────
const chained = server()
  .get("/c/r0/:id", (c) => ({ id: c.params.id }))
  .get("/c/r1/:id", (c) => ({ id: c.params.id }))
  .get("/c/r2/:id", (c) => ({ id: c.params.id }))
  .get("/c/r3/:id", (c) => ({ id: c.params.id }))
  .get("/c/r4/:id", (c) => ({ id: c.params.id }))
  .get("/c/r5/:id", (c) => ({ id: c.params.id }))
  .get("/c/r6/:id", (c) => ({ id: c.params.id }))
  .get("/c/r7/:id", (c) => ({ id: c.params.id }))
  .get("/c/r8/:id", (c) => ({ id: c.params.id }))
  .get("/c/r9/:id", (c) => ({ id: c.params.id }))
  .get("/c/r10/:id", (c) => ({ id: c.params.id }))
  .get("/c/r11/:id", (c) => ({ id: c.params.id }))
  .get("/c/r12/:id", (c) => ({ id: c.params.id }))
  .get("/c/r13/:id", (c) => ({ id: c.params.id }))
  .get("/c/r14/:id", (c) => ({ id: c.params.id }))
  .get("/c/r15/:id", (c) => ({ id: c.params.id }))
  .get("/c/r16/:id", (c) => ({ id: c.params.id }))
  .get("/c/r17/:id", (c) => ({ id: c.params.id }))
  .get("/c/r18/:id", (c) => ({ id: c.params.id }))
  .get("/c/r19/:id", (c) => ({ id: c.params.id }))
  .get("/c/r20/:id", (c) => ({ id: c.params.id }))
  .get("/c/r21/:id", (c) => ({ id: c.params.id }))
  .get("/c/r22/:id", (c) => ({ id: c.params.id }))
  .get("/c/r23/:id", (c) => ({ id: c.params.id }))
  .get("/c/r24/:id", (c) => ({ id: c.params.id }))
  .get("/c/r25/:id", (c) => ({ id: c.params.id }))
  .get("/c/r26/:id", (c) => ({ id: c.params.id }))
  .get("/c/r27/:id", (c) => ({ id: c.params.id }))
  .get("/c/r28/:id", (c) => ({ id: c.params.id }))
  .get("/c/r29/:id", (c) => ({ id: c.params.id }))
  .get("/c/r30/:id", (c) => ({ id: c.params.id }))
  .get("/c/r31/:id", (c) => ({ id: c.params.id }))
  .get("/c/r32/:id", (c) => ({ id: c.params.id }))
  .get("/c/r33/:id", (c) => ({ id: c.params.id }))
  .get("/c/r34/:id", (c) => ({ id: c.params.id }))
  .get("/c/r35/:id", (c) => ({ id: c.params.id }))
  .get("/c/r36/:id", (c) => ({ id: c.params.id }))
  .get("/c/r37/:id", (c) => ({ id: c.params.id }))
  .get("/c/r38/:id", (c) => ({ id: c.params.id }))
  .get("/c/r39/:id", (c) => ({ id: c.params.id }))
  .get("/c/r40/:id", (c) => ({ id: c.params.id }))
  .get("/c/r41/:id", (c) => ({ id: c.params.id }))
  .get("/c/r42/:id", (c) => ({ id: c.params.id }))
  .get("/c/r43/:id", (c) => ({ id: c.params.id }))
  .get("/c/r44/:id", (c) => ({ id: c.params.id }))
  .get("/c/r45/:id", (c) => ({ id: c.params.id }))
  .get("/c/r46/:id", (c) => ({ id: c.params.id }))
  .get("/c/r47/:id", (c) => ({ id: c.params.id }))
  .get("/c/r48/:id", (c) => ({ id: c.params.id }))
  .get("/c/r49/:id", (c) => ({ id: c.params.id }))
  .get("/c/r50/:id", (c) => ({ id: c.params.id }))
  .get("/c/r51/:id", (c) => ({ id: c.params.id }))
  .get("/c/r52/:id", (c) => ({ id: c.params.id }))
  .get("/c/r53/:id", (c) => ({ id: c.params.id }))
  .get("/c/r54/:id", (c) => ({ id: c.params.id }))
  .get("/c/r55/:id", (c) => ({ id: c.params.id }))
  .get("/c/r56/:id", (c) => ({ id: c.params.id }))
  .get("/c/r57/:id", (c) => ({ id: c.params.id }))
  .get("/c/r58/:id", (c) => ({ id: c.params.id }))
  .get("/c/r59/:id", (c) => ({ id: c.params.id }))
  .get("/c/r60/:id", (c) => ({ id: c.params.id }))
  .get("/c/r61/:id", (c) => ({ id: c.params.id }))
  .get("/c/r62/:id", (c) => ({ id: c.params.id }))
  .get("/c/r63/:id", (c) => ({ id: c.params.id }))
  .get("/c/r64/:id", (c) => ({ id: c.params.id }))
  .get("/c/r65/:id", (c) => ({ id: c.params.id }))
  .get("/c/r66/:id", (c) => ({ id: c.params.id }))
  .get("/c/r67/:id", (c) => ({ id: c.params.id }))
  .get("/c/r68/:id", (c) => ({ id: c.params.id }))
  .get("/c/r69/:id", (c) => ({ id: c.params.id }))
  .get("/c/r70/:id", (c) => ({ id: c.params.id }))
  .get("/c/r71/:id", (c) => ({ id: c.params.id }))
  .get("/c/r72/:id", (c) => ({ id: c.params.id }))
  .get("/c/r73/:id", (c) => ({ id: c.params.id }))
  .get("/c/r74/:id", (c) => ({ id: c.params.id }))
  .get("/c/r75/:id", (c) => ({ id: c.params.id }))
  .get("/c/r76/:id", (c) => ({ id: c.params.id }))
  .get("/c/r77/:id", (c) => ({ id: c.params.id }))
  .get("/c/r78/:id", (c) => ({ id: c.params.id }))
  .get("/c/r79/:id", (c) => ({ id: c.params.id }))
  .get("/c/r80/:id", (c) => ({ id: c.params.id }))
  .get("/c/r81/:id", (c) => ({ id: c.params.id }))
  .get("/c/r82/:id", (c) => ({ id: c.params.id }))
  .get("/c/r83/:id", (c) => ({ id: c.params.id }))
  .get("/c/r84/:id", (c) => ({ id: c.params.id }))
  .get("/c/r85/:id", (c) => ({ id: c.params.id }))
  .get("/c/r86/:id", (c) => ({ id: c.params.id }))
  .get("/c/r87/:id", (c) => ({ id: c.params.id }))
  .get("/c/r88/:id", (c) => ({ id: c.params.id }))
  .get("/c/r89/:id", (c) => ({ id: c.params.id }))

export type Chained = typeof chained

// ── 2. composition: 4 domain groups × 30 routes, merged — 120 routes, no ceiling ─────────────
const group0 = server()
  .get("/g0/r0/:id", (c) => ({ id: c.params.id, n: 0 }))
  .get("/g0/r1/:id", (c) => ({ id: c.params.id, n: 1 }))
  .get("/g0/r2/:id", (c) => ({ id: c.params.id, n: 2 }))
  .get("/g0/r3/:id", (c) => ({ id: c.params.id, n: 3 }))
  .get("/g0/r4/:id", (c) => ({ id: c.params.id, n: 4 }))
  .get("/g0/r5/:id", (c) => ({ id: c.params.id, n: 5 }))
  .get("/g0/r6/:id", (c) => ({ id: c.params.id, n: 6 }))
  .get("/g0/r7/:id", (c) => ({ id: c.params.id, n: 7 }))
  .get("/g0/r8/:id", (c) => ({ id: c.params.id, n: 8 }))
  .get("/g0/r9/:id", (c) => ({ id: c.params.id, n: 9 }))
  .get("/g0/r10/:id", (c) => ({ id: c.params.id, n: 10 }))
  .get("/g0/r11/:id", (c) => ({ id: c.params.id, n: 11 }))
  .get("/g0/r12/:id", (c) => ({ id: c.params.id, n: 12 }))
  .get("/g0/r13/:id", (c) => ({ id: c.params.id, n: 13 }))
  .get("/g0/r14/:id", (c) => ({ id: c.params.id, n: 14 }))
  .get("/g0/r15/:id", (c) => ({ id: c.params.id, n: 15 }))
  .get("/g0/r16/:id", (c) => ({ id: c.params.id, n: 16 }))
  .get("/g0/r17/:id", (c) => ({ id: c.params.id, n: 17 }))
  .get("/g0/r18/:id", (c) => ({ id: c.params.id, n: 18 }))
  .get("/g0/r19/:id", (c) => ({ id: c.params.id, n: 19 }))
  .get("/g0/r20/:id", (c) => ({ id: c.params.id, n: 20 }))
  .get("/g0/r21/:id", (c) => ({ id: c.params.id, n: 21 }))
  .get("/g0/r22/:id", (c) => ({ id: c.params.id, n: 22 }))
  .get("/g0/r23/:id", (c) => ({ id: c.params.id, n: 23 }))
  .get("/g0/r24/:id", (c) => ({ id: c.params.id, n: 24 }))
  .get("/g0/r25/:id", (c) => ({ id: c.params.id, n: 25 }))
  .get("/g0/r26/:id", (c) => ({ id: c.params.id, n: 26 }))
  .get("/g0/r27/:id", (c) => ({ id: c.params.id, n: 27 }))
  .get("/g0/r28/:id", (c) => ({ id: c.params.id, n: 28 }))
  .get("/g0/r29/:id", (c) => ({ id: c.params.id, n: 29 }))

const group1 = server()
  .get("/g1/r30/:id", (c) => ({ id: c.params.id, n: 30 }))
  .get("/g1/r31/:id", (c) => ({ id: c.params.id, n: 31 }))
  .get("/g1/r32/:id", (c) => ({ id: c.params.id, n: 32 }))
  .get("/g1/r33/:id", (c) => ({ id: c.params.id, n: 33 }))
  .get("/g1/r34/:id", (c) => ({ id: c.params.id, n: 34 }))
  .get("/g1/r35/:id", (c) => ({ id: c.params.id, n: 35 }))
  .get("/g1/r36/:id", (c) => ({ id: c.params.id, n: 36 }))
  .get("/g1/r37/:id", (c) => ({ id: c.params.id, n: 37 }))
  .get("/g1/r38/:id", (c) => ({ id: c.params.id, n: 38 }))
  .get("/g1/r39/:id", (c) => ({ id: c.params.id, n: 39 }))
  .get("/g1/r40/:id", (c) => ({ id: c.params.id, n: 40 }))
  .get("/g1/r41/:id", (c) => ({ id: c.params.id, n: 41 }))
  .get("/g1/r42/:id", (c) => ({ id: c.params.id, n: 42 }))
  .get("/g1/r43/:id", (c) => ({ id: c.params.id, n: 43 }))
  .get("/g1/r44/:id", (c) => ({ id: c.params.id, n: 44 }))
  .get("/g1/r45/:id", (c) => ({ id: c.params.id, n: 45 }))
  .get("/g1/r46/:id", (c) => ({ id: c.params.id, n: 46 }))
  .get("/g1/r47/:id", (c) => ({ id: c.params.id, n: 47 }))
  .get("/g1/r48/:id", (c) => ({ id: c.params.id, n: 48 }))
  .get("/g1/r49/:id", (c) => ({ id: c.params.id, n: 49 }))
  .get("/g1/r50/:id", (c) => ({ id: c.params.id, n: 50 }))
  .get("/g1/r51/:id", (c) => ({ id: c.params.id, n: 51 }))
  .get("/g1/r52/:id", (c) => ({ id: c.params.id, n: 52 }))
  .get("/g1/r53/:id", (c) => ({ id: c.params.id, n: 53 }))
  .get("/g1/r54/:id", (c) => ({ id: c.params.id, n: 54 }))
  .get("/g1/r55/:id", (c) => ({ id: c.params.id, n: 55 }))
  .get("/g1/r56/:id", (c) => ({ id: c.params.id, n: 56 }))
  .get("/g1/r57/:id", (c) => ({ id: c.params.id, n: 57 }))
  .get("/g1/r58/:id", (c) => ({ id: c.params.id, n: 58 }))
  .get("/g1/r59/:id", (c) => ({ id: c.params.id, n: 59 }))

const group2 = server()
  .get("/g2/r60/:id", (c) => ({ id: c.params.id, n: 60 }))
  .get("/g2/r61/:id", (c) => ({ id: c.params.id, n: 61 }))
  .get("/g2/r62/:id", (c) => ({ id: c.params.id, n: 62 }))
  .get("/g2/r63/:id", (c) => ({ id: c.params.id, n: 63 }))
  .get("/g2/r64/:id", (c) => ({ id: c.params.id, n: 64 }))
  .get("/g2/r65/:id", (c) => ({ id: c.params.id, n: 65 }))
  .get("/g2/r66/:id", (c) => ({ id: c.params.id, n: 66 }))
  .get("/g2/r67/:id", (c) => ({ id: c.params.id, n: 67 }))
  .get("/g2/r68/:id", (c) => ({ id: c.params.id, n: 68 }))
  .get("/g2/r69/:id", (c) => ({ id: c.params.id, n: 69 }))
  .get("/g2/r70/:id", (c) => ({ id: c.params.id, n: 70 }))
  .get("/g2/r71/:id", (c) => ({ id: c.params.id, n: 71 }))
  .get("/g2/r72/:id", (c) => ({ id: c.params.id, n: 72 }))
  .get("/g2/r73/:id", (c) => ({ id: c.params.id, n: 73 }))
  .get("/g2/r74/:id", (c) => ({ id: c.params.id, n: 74 }))
  .get("/g2/r75/:id", (c) => ({ id: c.params.id, n: 75 }))
  .get("/g2/r76/:id", (c) => ({ id: c.params.id, n: 76 }))
  .get("/g2/r77/:id", (c) => ({ id: c.params.id, n: 77 }))
  .get("/g2/r78/:id", (c) => ({ id: c.params.id, n: 78 }))
  .get("/g2/r79/:id", (c) => ({ id: c.params.id, n: 79 }))
  .get("/g2/r80/:id", (c) => ({ id: c.params.id, n: 80 }))
  .get("/g2/r81/:id", (c) => ({ id: c.params.id, n: 81 }))
  .get("/g2/r82/:id", (c) => ({ id: c.params.id, n: 82 }))
  .get("/g2/r83/:id", (c) => ({ id: c.params.id, n: 83 }))
  .get("/g2/r84/:id", (c) => ({ id: c.params.id, n: 84 }))
  .get("/g2/r85/:id", (c) => ({ id: c.params.id, n: 85 }))
  .get("/g2/r86/:id", (c) => ({ id: c.params.id, n: 86 }))
  .get("/g2/r87/:id", (c) => ({ id: c.params.id, n: 87 }))
  .get("/g2/r88/:id", (c) => ({ id: c.params.id, n: 88 }))
  .get("/g2/r89/:id", (c) => ({ id: c.params.id, n: 89 }))

const group3 = server()
  .get("/g3/r90/:id", (c) => ({ id: c.params.id, n: 90 }))
  .get("/g3/r91/:id", (c) => ({ id: c.params.id, n: 91 }))
  .get("/g3/r92/:id", (c) => ({ id: c.params.id, n: 92 }))
  .get("/g3/r93/:id", (c) => ({ id: c.params.id, n: 93 }))
  .get("/g3/r94/:id", (c) => ({ id: c.params.id, n: 94 }))
  .get("/g3/r95/:id", (c) => ({ id: c.params.id, n: 95 }))
  .get("/g3/r96/:id", (c) => ({ id: c.params.id, n: 96 }))
  .get("/g3/r97/:id", (c) => ({ id: c.params.id, n: 97 }))
  .get("/g3/r98/:id", (c) => ({ id: c.params.id, n: 98 }))
  .get("/g3/r99/:id", (c) => ({ id: c.params.id, n: 99 }))
  .get("/g3/r100/:id", (c) => ({ id: c.params.id, n: 100 }))
  .get("/g3/r101/:id", (c) => ({ id: c.params.id, n: 101 }))
  .get("/g3/r102/:id", (c) => ({ id: c.params.id, n: 102 }))
  .get("/g3/r103/:id", (c) => ({ id: c.params.id, n: 103 }))
  .get("/g3/r104/:id", (c) => ({ id: c.params.id, n: 104 }))
  .get("/g3/r105/:id", (c) => ({ id: c.params.id, n: 105 }))
  .get("/g3/r106/:id", (c) => ({ id: c.params.id, n: 106 }))
  .get("/g3/r107/:id", (c) => ({ id: c.params.id, n: 107 }))
  .get("/g3/r108/:id", (c) => ({ id: c.params.id, n: 108 }))
  .get("/g3/r109/:id", (c) => ({ id: c.params.id, n: 109 }))
  .get("/g3/r110/:id", (c) => ({ id: c.params.id, n: 110 }))
  .get("/g3/r111/:id", (c) => ({ id: c.params.id, n: 111 }))
  .get("/g3/r112/:id", (c) => ({ id: c.params.id, n: 112 }))
  .get("/g3/r113/:id", (c) => ({ id: c.params.id, n: 113 }))
  .get("/g3/r114/:id", (c) => ({ id: c.params.id, n: 114 }))
  .get("/g3/r115/:id", (c) => ({ id: c.params.id, n: 115 }))
  .get("/g3/r116/:id", (c) => ({ id: c.params.id, n: 116 }))
  .get("/g3/r117/:id", (c) => ({ id: c.params.id, n: 117 }))
  .get("/g3/r118/:id", (c) => ({ id: c.params.id, n: 118 }))
  .get("/g3/r119/:id", (c) => ({ id: c.params.id, n: 119 }))

const app = server()
  .get("/health", () => ({ ok: true }))
  .merge(group0)
  .merge(group1)
  .merge(group2)
  .merge(group3)

export type App = typeof app

// Full type fidelity across the merged registry: params stay exact per route.
const typed = server()
  .merge(group0)
  .get("/after/:uid", (c) => ({ uid: c.params.uid }))

// @ts-expect-error — a param that does not exist on the path must still be rejected
const bad = typed.get("/strict/:one", (c) => c.params.two)
void bad

export type Typed = typeof typed
