import { inProcessClient } from "@nifrajs/client"
import { toFetchHandler } from "@nifrajs/core/server"
import { createWebApp } from "@nifrajs/web"
import { reactAdapter } from "@nifrajs/web-react"
import { backend } from "./backend"
// Generated by build.ts (buildServer): the static-import route manifest + baked client entry URL.
import { clientEntry, manifest } from "./server-manifest"

const app = createWebApp({
  adapter: reactAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra",
})

const handler = toFetchHandler(app)
// Exact arg tuple of the SSR handler's fetch - keeps env/ctx strongly typed without `any`.
type FetchArgs = Parameters<typeof handler.fetch>

// Cloudflare Pages advanced mode (`_worker.js`): this handles requests; Pages serves matching
// static assets (the client bundle in /assets/*) first, falling through here for SSR.
export default {
  fetch(...args: FetchArgs): ReturnType<typeof handler.fetch> {
    const [request] = args
    const url = new URL(request.url)
    // The docs MCP now runs on its own always-on origin (mcp.nifra.dev), so its traffic never counts
    // against this Pages deployment's request budget. Anything still pointed at the old path gets a
    // permanent redirect: 308 preserves the POST method + body, so an MCP client re-sends its JSON-RPC to
    // the new origin unchanged. Serving the same redirect as an edge Redirect Rule keeps even this off the
    // worker (then /mcp never invokes Pages Functions).
    if (url.pathname === "/mcp")
      return Promise.resolve(Response.redirect("https://mcp.nifra.dev/", 308))
    return handler.fetch(...args)
  },
}
