import { docsTools, type Example, respondMcpHttp } from "@nifrajs/cli/mcp"
import { inProcessClient } from "@nifrajs/client"
import { toFetchHandler } from "@nifrajs/core"
import { UI_MIME } from "@nifrajs/mcp"
import { createWebApp } from "@nifrajs/web"
import { reactAdapter } from "@nifrajs/web-react"
import { backend } from "./backend"
import { examplesAppTool, examplesWidget } from "./mcp-app"
// Generated by build.ts (buildServer): the static-import route manifest + baked client entry URL.
import { clientEntry, manifest } from "./server-manifest"

const app = createWebApp({
  adapter: reactAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra",
})

let cachedDocs: string | undefined
let cachedExamples: Example[] | undefined

async function loadDocs(requestUrl: string): Promise<string | undefined> {
  if (cachedDocs) return cachedDocs
  try {
    const url = new URL("/llms-full.txt", requestUrl).toString()
    const res = await fetch(url)
    if (res.ok) {
      cachedDocs = await res.text()
      return cachedDocs
    }
  } catch (e) {
    console.error("Failed to fetch docs corpus in worker", e)
  }
  return undefined
}

async function loadExamples(requestUrl: string): Promise<Example[] | undefined> {
  if (cachedExamples) return cachedExamples
  try {
    const url = new URL("/examples.json", requestUrl).toString()
    const res = await fetch(url)
    if (res.ok) {
      cachedExamples = (await res.json()) as Example[]
      return cachedExamples
    }
  } catch (e) {
    console.error("Failed to fetch examples corpus in worker", e)
  }
  return undefined
}

const handler = toFetchHandler(app)
// Exact arg tuple of the SSR handler's fetch — keeps env/ctx strongly typed without `any`.
type FetchArgs = Parameters<typeof handler.fetch>

// Cloudflare Pages advanced mode (`_worker.js`): this handles requests; Pages serves matching
// static assets (the client bundle in /assets/*) first, falling through here for SSR.
export default {
  fetch(...args: FetchArgs): ReturnType<typeof handler.fetch> {
    const [request] = args
    const url = new URL(request.url)
    if (url.pathname === "/mcp") {
      // Public read-only docs MCP — `respondMcpHttp` validates method + caps the body at 1 MB. nifra's
      // own MCP is also an MCP App: `nifra_examples_app` renders the examples in the `examplesWidget`.
      const tools = [
        ...docsTools(
          () => loadDocs(request.url),
          () => loadExamples(request.url),
        ),
        examplesAppTool(() => loadExamples(request.url)),
      ]
      return respondMcpHttp(request, tools, {
        features: { resources: [examplesWidget.resource], ui: { mimeTypes: [UI_MIME] } },
      })
    }
    return handler.fetch(...args)
  },
}
