import { inProcessClient } from "@nifrajs/client"
import { toFetchHandler } from "@nifrajs/core/server"
import { createWebApp } from "@nifrajs/web"
import { solidAdapter } from "@nifrajs/web-solid"
import { backend } from "./backend"
// Generated by `build.ts` (buildServer) — the static-import route manifest + the baked client entry
// URL. No node:fs, no dynamic-path import, so it runs on workerd.
import { clientEntry, manifest } from "./server-manifest"

const app = createWebApp({
  adapter: solidAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra on the edge",
})

// Assets-first: wrangler serves /assets/* from ./public directly; non-asset paths fall through to
// the worker (SSR). `toFetchHandler` threads the Workers platform into nifra's context (c.env etc.).
export default toFetchHandler(app)
