import { describe, expect, test } from "bun:test"
import {
  loadDocsCorpus,
  renderDocsResult,
  searchSections,
  splitSections,
} from "../src/docs-search.ts"

const DOC = [
  "# nifra — full developer documentation",
  "Intro paragraph about the framework.",
  "## WebSockets",
  "app.ws() registers a typed WebSocket route. Import @nifrajs/core/ws once at the entry.",
  "## ISR & caching",
  "withISR wraps a web app; revalidate via the __nifra/revalidate endpoint with a token.",
  "## Auth & sessions",
  "Sessions are signed cookies. revalidate is unrelated here but mentioned once.",
].join("\n")

describe("splitSections", () => {
  test("splits on ## and keeps the intro as Overview", () => {
    const sections = splitSections(DOC)
    expect(sections.map((s) => s.heading)).toEqual([
      "Overview",
      "WebSockets",
      "ISR & caching",
      "Auth & sessions",
    ])
  })
})

describe("searchSections", () => {
  test("heading hits outrank body mentions", () => {
    const sections = splitSections(DOC)
    const top = searchSections(sections, "isr revalidate", 2)
    expect(top[0]?.heading).toBe("ISR & caching")
  })

  test("matches common agent aliases and stems", () => {
    const sections = splitSections(DOC)
    expect(searchSections(sections, "authentication", 1)[0]?.heading).toBe("Auth & sessions")
    expect(searchSections(sections, "ws", 1)[0]?.heading).toBe("WebSockets")
  })

  test("no terms or no hits → empty", () => {
    const sections = splitSections(DOC)
    expect(searchSections(sections, "", 3)).toEqual([])
    expect(searchSections(sections, "kubernetes", 3)).toEqual([])
  })
})

describe("renderDocsResult", () => {
  test("no query → section index, not content", () => {
    const out = renderDocsResult(DOC, undefined, 3)
    expect(out).toContain("- WebSockets")
    expect(out).not.toContain("app.ws() registers")
  })

  test("query → matching section content only", () => {
    const out = renderDocsResult(DOC, "websocket entry import", 1)
    expect(out).toContain("## WebSockets")
    expect(out).toContain("@nifrajs/core/ws")
    expect(out).not.toContain("withISR")
  })

  test("oversized sections are trimmed with a pointer", () => {
    const big = `## Huge\n${"x".repeat(5000)}`
    const out = renderDocsResult(big, "huge", 1)
    expect(out.length).toBeLessThan(3500)
    expect(out).toContain("(trimmed")
  })

  test("no match → actionable message", () => {
    expect(renderDocsResult(DOC, "zzz-nothing", 3)).toContain("section index")
  })
})

describe("bundled corpus", () => {
  test("loads and finds real sections (generated by gen:llms)", async () => {
    const corpus = await loadDocsCorpus()
    expect(corpus).toBeDefined()
    const out = renderDocsResult(corpus as string, "websockets pub sub", 2)
    expect(out).toContain("##")
    expect(out.length).toBeLessThan(12_000) // the point: a slice, never the 150 KB dump
  })
})
