import { describe, expect, test } from "bun:test"
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { runReview } from "../src/review.ts"

const manifestSource = (routeFiles: readonly string[]): string =>
  [
    "// GENERATED by @nifrajs/web generateServerManifest - review fixture",
    'import { buildManifest, type RouteModule } from "@nifrajs/web"',
    ...routeFiles.map(
      (file, index) => `import * as m${index} from "./routes/${file.replace(/\.[jt]sx?$/, "")}"`,
    ),
    "const modules: Record<string, RouteModule> = {",
    ...routeFiles.map((file, index) => `  ${JSON.stringify(file)}: m${index},`),
    "}",
    'export const clientEntry = "/assets/_nifra-entry-test.js"',
    "export const manifest = buildManifest(Object.keys(modules), (file) => Promise.resolve(modules[file]))",
  ].join("\n")

async function manifestProject(): Promise<{ root: string; manifest: string }> {
  const root = await mkdtemp(join(tmpdir(), "nifra-review-fix-"))
  await mkdir(join(root, "routes"), { recursive: true })
  await mkdir(join(root, "node_modules", "typescript", "bin"), { recursive: true })
  await writeFile(
    join(root, "package.json"),
    JSON.stringify({ name: "review-fix-fixture", dependencies: { "@nifrajs/web": "3.4.0" } }),
  )
  await writeFile(join(root, "tsconfig.json"), JSON.stringify({ files: [] }))
  await writeFile(join(root, "node_modules", "typescript", "bin", "tsc"), "process.exit(0)\n")
  await writeFile(
    join(root, "routes", "index.tsx"),
    "export default function Index() { return null }\n",
  )
  await writeFile(
    join(root, "routes", "new.tsx"),
    "export default function New() { return null }\n",
  )
  const manifest = join(root, "server-manifest.ts")
  await writeFile(manifest, manifestSource(["index.tsx"]))
  return { root, manifest }
}

describe("nifra review safe fixes", () => {
  test("plan-only and dry-run never invoke a recipe or mutate the project", async () => {
    const { root, manifest } = await manifestProject()
    try {
      const before = await readFile(manifest, "utf8")
      for (const input of [{ fix: true }, { fix: true, dryRun: true }] as const) {
        const report = await runReview(input, { cwd: root })
        expect(report.status).toBe("fail")
        expect(report.fixes).toEqual([{ recipe: "manifest.sync", status: "planned" }])
        expect(await readFile(manifest, "utf8")).toBe(before)
      }
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  test("write mode applies only the allowlisted recipe and reruns the complete review", async () => {
    const { root, manifest } = await manifestProject()
    try {
      const report = await runReview({ fix: true, write: true }, { cwd: root })
      expect(report.status).toBe("pass")
      expect(report.findings.some((finding) => finding.code === "NF-C012")).toBe(false)
      expect(report.fixes).toEqual([
        { recipe: "manifest.sync", status: "changed", changedPaths: ["server-manifest.ts"] },
      ])
      expect(await readFile(manifest, "utf8")).toContain('"new.tsx"')
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })

  test("a fix request cannot authorize a recipe outside the public allowlist", async () => {
    const { root } = await manifestProject()
    try {
      const report = await runReview({ fix: true }, { cwd: root })
      expect(
        report.findings.every(
          (finding) =>
            finding.fix === undefined ||
            ["manifest.sync", "workspace-dist.rebuild"].includes(finding.fix.recipe),
        ),
      ).toBe(true)
      expect(report.fixes?.map((fix) => fix.recipe)).not.toContain("contracts.snapshot")
    } finally {
      await rm(root, { recursive: true, force: true })
    }
  })
})
