import { expect, test } from "bun:test"
import {
  buildManifest,
  generateClientEntry,
  type RenderAdapter,
  ROOT_ATTRIBUTE,
  type RouteModule,
  renderPage,
} from "../src/index.ts"

/**
 * The server's container and the client entry's lookup are generated by two different functions at two
 * different times - `rootId` is chosen per RENDER, the entry is emitted once per BUILD - and nothing in
 * the type system couples them. So the entry hardcoded `getElementById("root")` and swallowed the miss
 * with `if (root)`: `renderPage({ rootId: "app" })` served a flawless server-rendered document that
 * hydrated nothing, forever, with an empty console. Every test here drives BOTH sides, because a test
 * that only reads the markup or only reads the generated source is exactly what missed this.
 */

const streamOf = (s: string): ReadableStream<Uint8Array> =>
  new ReadableStream({
    start(c) {
      c.enqueue(new TextEncoder().encode(s))
      c.close()
    },
  })
const stub: RenderAdapter = {
  renderToStream: (chain, props) =>
    streamOf(`<p>chain=${chain.length}:${JSON.stringify(props.data)}</p>`),
  hydrationHead: () => "",
}

const entrySource = (): string =>
  generateClientEntry(
    buildManifest(["index.tsx"], (file) => async (): Promise<RouteModule> => ({ default: file })),
    { clientModule: "@nifrajs/web-solid/client", resolve: (file) => `/routes/${file}` },
  )

/** The container `<div>` as the server actually wrote it, id and attributes kept apart. */
const containerOf = (html: string): { readonly id: string; readonly attributes: string } => {
  const match = /<body><div id="([^"]*)"([^>]*)>/.exec(html)
  if (match === null)
    throw new Error(`no container in the rendered document:\n${html.slice(0, 400)}`)
  return { id: match[1] as string, attributes: match[2] as string }
}

/**
 * A document holding one element - the container the server emitted, or nothing at all.
 *
 * `querySelector` genuinely tests for the attribute and `getElementById` genuinely compares the id, so
 * renaming the marker on one side alone makes these tests fail rather than pass on a stale agreement.
 */
const documentWith = (container: { readonly id: string; readonly attributes: string } | null) => {
  const element = { tagName: "DIV" }
  return {
    querySelector(selector: string): object | null {
      const attribute = /^\[([a-z-]+)\]$/.exec(selector)
      if (attribute === null) throw new Error(`this stub only supports [attr], got ${selector}`)
      if (container === null) return null
      return new RegExp(`(^|\\s)${attribute[1] as string}(\\s|=|$)`).test(container.attributes)
        ? element
        : null
    },
    getElementById: (id: string): object | null =>
      container !== null && container.id === id ? element : null,
  }
}

/**
 * Run the generated entry's container lookup - the real emitted lines, not a copy - against a document.
 *
 * Slicing source out of a generated string is brittle by nature, so the shape is asserted rather than
 * assumed: if the lookup moves or grows a line, this throws instead of silently testing nothing.
 */
const findRoot = (document: object): object | null => {
  const lines = entrySource().split("\n")
  const start = lines.findIndex((line) => line.startsWith("const root = "))
  const guard = lines.findIndex((line) => line.startsWith("if (!root)"))
  if (start === -1 || guard !== start + 1) {
    throw new Error("the generated entry's container lookup moved - update this test with it")
  }
  const lookup = lines.slice(start, guard + 1).join("\n")
  return new Function("document", `${lookup}\nreturn root`)(document) as object | null
}

test("a default render stays byte-identical: no marker, and the entry still finds #root", async () => {
  const html = await (
    await renderPage({ adapter: stub, chain: [null], data: null, clientEntry: "/c.js" })
  ).text()
  expect(html).toContain('<div id="root">')
  expect(html).not.toContain(ROOT_ATTRIBUTE)

  expect(findRoot(documentWith(containerOf(html)))).not.toBeNull()
})

test("a custom rootId is marked, and the entry hydrates THAT container", async () => {
  const html = await (
    await renderPage({
      adapter: stub,
      chain: [null],
      data: null,
      clientEntry: "/c.js",
      rootId: "app",
    })
  ).text()
  const container = containerOf(html)
  expect(container.id).toBe("app")
  expect(container.attributes).toContain(ROOT_ATTRIBUTE)

  // The bug, stated as a test: before the marker this returned null and the page never hydrated.
  expect(findRoot(documentWith(container))).not.toBeNull()
  // ...and the reason it returned null - there is no `#root` in this document to fall back to.
  expect(documentWith(container).getElementById("root")).toBeNull()
})

test("an id that is not a valid selector still works - the marker is looked up, not the id", async () => {
  // A rootId is escaped into an attribute VALUE, so ids that would break a CSS selector are legal
  // markup. Finding the container by a fixed attribute means none of them need escaping twice.
  const html = await (
    await renderPage({
      adapter: stub,
      chain: [null],
      data: null,
      clientEntry: "/c.js",
      rootId: 'r"><x',
    })
  ).text()
  const container = containerOf(html)
  expect(container.id).toBe("r&quot;&gt;&lt;x")
  expect(findRoot(documentWith(container))).not.toBeNull()
})

test("a document with no container throws, naming the container it wanted", () => {
  expect(() => findRoot(documentWith(null))).toThrow(/no hydration container/)
  expect(() => findRoot(documentWith(null))).toThrow(new RegExp(ROOT_ATTRIBUTE))
})

test("the entry never bakes in an id other than the documented fallback", () => {
  const source = entrySource()
  // `getElementById("root")` is the fallback for an unmarked default document and is meant to be
  // here. A SECOND baked id would be the same bug wearing a different name.
  expect(source.match(/getElementById\("[^"]*"\)/g)).toEqual(['getElementById("root")'])
  expect(source).toContain(`document.querySelector("[${ROOT_ATTRIBUTE}]")`)
})
