/**
 * `@nifrajs/web/route-types` - the generated `./+types/<route>` modules.
 *
 * Every route file gets `.nifra/types/<routes>/<dir>/+types/<name>.d.ts`, declaring a `Route`
 * namespace: the route's `Params`, the `LoaderData` and `ActionData` its output schemas let through,
 * the `LoaderArgs` its backend half receives, and its component's props. With
 * `"rootDirs": [".", "./.nifra/types"]` in tsconfig, both halves of a route import it as
 * `./+types/<name>`:
 *
 *     // routes/blog/[slug].tsx
 *     import type { Route } from "./+types/[slug]"
 *     export default function Post({ data }: Route.ComponentProps) { ... }
 *
 *     // routes/blog/[slug].backend.ts
 *     export async function loader({ api, params }: Route.LoaderArgs) { ... }
 *
 * `LoaderData` is the output type of `loaderOutput`, not the loader's return type: the data guard
 * projects the loader's value through that schema, so the schema is what the component receives.
 * `.nifra/types/register.d.ts` registers `backend/app.ts`'s `backend` with `@nifrajs/client`, so `api`
 * is typed without a route importing the backend.
 */
import {
  type Dirent,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { dirname, join, relative } from "node:path"
import {
  buildManifest,
  isMiddlewareFile,
  isRouteBackendFile,
  type LayoutEntry,
  type Manifest,
} from "./manifest.ts"

/** Where the generated types live, relative to the app root. */
export const ROUTE_TYPES_DIR = ".nifra/types"

const BACKEND_APP = "backend/app"
const SCRIPT_EXTS = [".ts", ".tsx", ".js", ".jsx"] as const

export interface RouteTypesOptions {
  /** The app root: where `.nifra/` and `backend/app.ts` live. */
  readonly appRoot: string
  /** The routes directory. Defaults to `<appRoot>/routes`. */
  readonly routesDir?: string
}

type Kind = "page" | "layout"

interface RouteFile {
  readonly file: string
  readonly backend: string | undefined
  readonly kind: Kind
}

const posix = (path: string): string => path.replaceAll("\\", "/")

/** Every route file the router serves, once each: pages, layouts and the special pages. */
function routeFiles(manifest: Manifest): readonly RouteFile[] {
  const files = new Map<string, RouteFile>()
  const add = (entry: Pick<LayoutEntry, "file" | "backend">, kind: Kind): void => {
    if (!files.has(entry.file))
      files.set(entry.file, { file: entry.file, backend: entry.backend, kind })
  }
  for (const route of manifest.routes) add(route, "page")
  for (const layout of Object.values(manifest.layouts)) add(layout, "layout")
  for (const group of [
    manifest.errors,
    manifest.notFounds,
    manifest.statusPages,
    manifest.loadings,
  ]) {
    for (const entry of Object.values(group ?? {})) add(entry, "page")
  }
  if (manifest.notFound !== undefined) add(manifest.notFound, "page")
  return [...files.values()].sort((a, b) => a.file.localeCompare(b.file))
}

const PARAM = /^\[([A-Za-z_][A-Za-z0-9_]*)\]$/
const OPTIONAL = /^\[\[([A-Za-z_][A-Za-z0-9_]*)\]\]$/
const CATCH_ALL = /^\[\.\.\.([A-Za-z_][A-Za-z0-9_]*)\]$/

/** The params a route file's URL carries: its directories', plus its own name's for a page. */
function paramsType(file: string, kind: Kind): string {
  const segments = file.replace(/\.[^./]+$/, "").split("/")
  const own =
    kind === "page" && !segments.at(-1)?.startsWith("_") ? segments : segments.slice(0, -1)
  const fields: string[] = []
  for (const segment of own) {
    const optional = OPTIONAL.exec(segment)
    const name = optional?.[1] ?? PARAM.exec(segment)?.[1] ?? CATCH_ALL.exec(segment)?.[1]
    if (name !== undefined) fields.push(`readonly ${name}${optional === null ? "" : "?"}: string`)
  }
  return fields.length === 0 ? "Record<string, never>" : `{ ${fields.join("; ")} }`
}

/** A module specifier for `target` from a file in `fromDir`, without a script extension. */
function specifier(fromDir: string, target: string): string {
  let path = posix(relative(fromDir, target))
  for (const ext of SCRIPT_EXTS) if (path.endsWith(ext)) path = path.slice(0, -ext.length)
  return path.startsWith(".") ? path : `./${path}`
}

const backendAppOf = (appRoot: string): string | undefined =>
  SCRIPT_EXTS.map((ext) => join(appRoot, `${BACKEND_APP}${ext}`)).find((path) => existsSync(path))

function routeTypesModule(
  route: RouteFile,
  out: string,
  routesDir: string,
  label: string,
  register: string | undefined,
): string {
  const dir = dirname(out)
  const backend = route.backend === undefined ? undefined : join(routesDir, route.backend)
  // Only a script module's exports are visible to TypeScript; a .svelte/.vue/.mdx one is an ambient shim.
  const frontend = /\.[jt]sx?$/.test(route.file) ? join(routesDir, route.file) : undefined
  const lines = [`// Generated by nifra from ${label}. Do not edit: \`nifra types\` rewrites it.`]
  if (register !== undefined)
    lines.push(`/// <reference path="${posix(relative(dir, register))}" />`)
  lines.push('import type { OutputOf, RouteLoaderArgs, SearchSchemaOf } from "@nifrajs/client"')
  if (route.kind === "page") lines.push('import type { RenderProps } from "@nifrajs/web"')
  lines.push("")
  if (backend !== undefined)
    lines.push(`type Backend = typeof import("${specifier(dir, backend)}")`)
  if (frontend !== undefined)
    lines.push(`type Frontend = typeof import("${specifier(dir, frontend)}")`)
  if (backend !== undefined || frontend !== undefined) lines.push("")
  const output = (name: string) => (backend === undefined ? "null" : `OutputOf<Backend, "${name}">`)
  lines.push(
    "export namespace Route {",
    "  /** The URL params this route's path carries. */",
    `  export type Params = ${paramsType(route.file, route.kind)}`,
    "  /** What the loader sends to the browser: the output type of `loaderOutput`. */",
    `  export type LoaderData = ${output("loaderOutput")}`,
    "  /** What the action sends back: the output type of `actionOutput`. */",
    `  export type ActionData = ${output("actionOutput")}`,
    "  /** The context the backend half's loader receives. */",
    `  export type LoaderArgs = RouteLoaderArgs<Params${frontend === undefined ? "" : ", SearchSchemaOf<Frontend>"}>`,
    "  /** The context the backend half's action receives. */",
    "  export type ActionArgs = LoaderArgs",
  )
  if (route.kind === "page") {
    lines.push(
      "  /** The page component's props. */",
      '  export type ComponentProps = Omit<RenderProps, "data" | "actionData" | "params"> & {',
      "    readonly data: LoaderData",
      "    readonly actionData?: ActionData",
      "    readonly params: Params",
      "  }",
    )
  } else {
    lines.push(
      "  /** The layout component's props; `Children` is the adapter's children type. */",
      "  export type ComponentProps<Children = unknown> = {",
      "    readonly data: LoaderData",
      "    readonly children?: Children",
      "  }",
    )
  }
  lines.push("}", "")
  return lines.join("\n")
}

function registerModule(out: string, backendApp: string, label: string): string {
  return [
    `// Generated by nifra from ${label}. Do not edit: \`nifra types\` rewrites it.`,
    `import type { backend } from "${specifier(dirname(out), backendApp)}"`,
    "",
    'declare module "@nifrajs/client" {',
    "  interface Register {",
    "    readonly backend: typeof backend",
    "  }",
    "}",
    "",
  ].join("\n")
}

/** Every generated types file for the app, by absolute path. */
export function routeTypeFiles(options: RouteTypesOptions): ReadonlyMap<string, string> {
  const appRoot = options.appRoot
  const routesDir = options.routesDir ?? join(appRoot, "routes")
  const typesRoot = join(appRoot, ROUTE_TYPES_DIR)
  const files = new Map<string, string>()
  const backendApp = backendAppOf(appRoot)
  const register = backendApp === undefined ? undefined : join(typesRoot, "register.d.ts")
  if (backendApp !== undefined && register !== undefined) {
    files.set(register, registerModule(register, backendApp, posix(relative(appRoot, backendApp))))
  }
  if (!existsSync(routesDir)) return files
  const listed = (readdirSync(routesDir, { recursive: true }) as string[])
    .map(posix)
    .filter(
      (file) =>
        /\.(?:tsx|jsx|svelte|vue|mdx)$/.test(file) ||
        isRouteBackendFile(file) ||
        isMiddlewareFile(file),
    )
  // Discovery only: the importer is never called.
  const manifest = buildManifest(listed, () => () => Promise.reject(new Error("not loaded")))
  const routesRel = posix(relative(appRoot, routesDir))
  for (const route of routeFiles(manifest)) {
    const dir = dirname(route.file)
    const name = route.file.slice(dir === "." ? 0 : dir.length + 1).replace(/\.[^.]+$/, "")
    const out = join(typesRoot, routesRel, dir === "." ? "" : dir, "+types", `${name}.d.ts`)
    files.set(out, routeTypesModule(route, out, routesDir, `${routesRel}/${route.file}`, register))
  }
  return files
}

/** Generated files missing or different on disk, and files on disk the app no longer generates. */
export function staleRouteTypes(options: RouteTypesOptions): readonly string[] {
  const files = routeTypeFiles(options)
  const stale: string[] = []
  for (const [path, content] of files) {
    if (!existsSync(path) || readFileSync(path, "utf8") !== content) stale.push(path)
  }
  for (const path of onDisk(join(options.appRoot, ROUTE_TYPES_DIR))) {
    if (!files.has(path)) stale.push(path)
  }
  return stale.sort()
}

function onDisk(dir: string): readonly string[] {
  if (!existsSync(dir)) return []
  return (readdirSync(dir, { recursive: true, withFileTypes: true }) as Dirent[])
    .filter((entry) => entry.isFile())
    .map((entry) => join(entry.parentPath, entry.name))
}

export interface RouteTypesResult {
  /** Files written because they were missing or out of date. */
  readonly written: readonly string[]
  /** Files removed because no route generates them any more. */
  readonly removed: readonly string[]
}

/**
 * Bring `.nifra/types` up to date with the app's routes. Unchanged files are left alone, so an
 * editor watching them sees only real changes. Owns the directory: anything else in it is removed.
 */
export function writeRouteTypes(options: RouteTypesOptions): RouteTypesResult {
  const files = routeTypeFiles(options)
  const written: string[] = []
  const removed: string[] = []
  for (const [path, content] of files) {
    if (existsSync(path) && readFileSync(path, "utf8") === content) continue
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    written.push(path)
  }
  for (const path of onDisk(join(options.appRoot, ROUTE_TYPES_DIR))) {
    if (files.has(path)) continue
    rmSync(path)
    removed.push(path)
  }
  return { written: written.sort(), removed: removed.sort() }
}
