/**
 * The `nifra dev --bun` boundary-plugin channel.
 *
 * Bun's dev-server bundling (`Bun.serve` HTML imports) accepts plugins ONLY through bunfig's
 * `[serve.static] plugins` - there is no programmatic option (upstream ask: oven-sh/bun#36830), and
 * a runtime `Bun.plugin()` never reaches it. Without a plugin there, a `*.fn` server-function module
 * would ship to the browser WHOLE (body, DB handles, secrets) instead of as the RPC stub the
 * production client build emits, and a `*.server` module would ship instead of being emptied.
 *
 * So the CLI generates, under `.nifra/dev-bun/`:
 *   - `boundary-plugin.ts` - default-exports one plugin composing the SAME `serverFnStubPlugin` +
 *     `serverOnlyEmptyPlugin` the production build uses (imported from `@nifrajs/web/build`, resolved
 *     from the app - identical stubs, not a re-implementation);
 *   - `bunfig.toml` - `[serve.static] plugins` naming that module (absolute path: bunfig resolves
 *     relative entries against the CONFIG file's directory, not the app), MERGED with the app's own
 *     bunfig: its `preload` and any `[serve.static] plugins` it declares are carried over, ours
 *     first so the boundary is stripped before any user transform sees the module.
 *
 * `dev --bun` then re-execs itself once with `--config=<generated>` (bunfig is read at process
 * start, so the already-running CLI can't adopt it) - see `cli.ts`. Everything else about the dev
 * loop is unchanged.
 */
import { mkdirSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"

/** TOML string literal: basic (double-quoted) form with the two escapes it needs. */
function tomlString(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`
}

/** The slice of the app's own bunfig this merge honors. */
export interface UserBunfigSlice {
  readonly preload: readonly string[]
  readonly serveStaticPlugins: readonly string[]
}

/** Parse the app's bunfig for the fields the generated config must carry over. Absent file or
 * malformed fields → empty slice (the generated config then only adds the boundary plugin). */
export function userBunfigSlice(toml: string | undefined): UserBunfigSlice {
  if (toml === undefined) return { preload: [], serveStaticPlugins: [] }
  let parsed: unknown
  try {
    parsed = Bun.TOML.parse(toml)
  } catch {
    return { preload: [], serveStaticPlugins: [] }
  }
  const root = (parsed ?? {}) as Record<string, unknown>
  const strings = (value: unknown): string[] =>
    Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : []
  const preload = strings(root.preload).length
    ? strings(root.preload)
    : typeof root.preload === "string"
      ? [root.preload]
      : []
  const serve = (root.serve ?? {}) as Record<string, unknown>
  const serveStatic = (serve.static ?? {}) as Record<string, unknown>
  return { preload, serveStaticPlugins: strings(serveStatic.plugins) }
}

/** Render the generated bunfig: the boundary plugin first, then the app's own serve.static plugins,
 * plus its preload entries. Relative user entries are resolved against the APP root before being
 * written, because bunfig resolves them against the config file's own directory. */
export function renderDevBunfig(
  boundaryPluginPath: string,
  user: UserBunfigSlice,
  appRoot: string,
): string {
  const resolveEntry = (entry: string): string =>
    entry.startsWith(".") ? resolve(appRoot, entry) : entry
  const plugins = [boundaryPluginPath, ...user.serveStaticPlugins.map(resolveEntry)]
  const lines = [
    "# Generated by `nifra dev --bun` - do not edit. Regenerated on every dev start.",
    "# Delivers the client-boundary plugins (server-fn stubs, server-only emptying) to Bun's",
    "# dev-server bundler, which only accepts plugins via [serve.static] (oven-sh/bun#36830).",
  ]
  if (user.preload.length > 0) {
    lines.push(`preload = [${user.preload.map((p) => tomlString(resolveEntry(p))).join(", ")}]`)
  }
  lines.push("", "[serve.static]", `plugins = [${plugins.map(tomlString).join(", ")}]`)
  return `${lines.join("\n")}\n`
}

/** The generated plugin module: compose the two production boundary plugins into one default
 * export. Import specifiers are bare so they resolve from the APP's install (the module lives
 * under the app's `.nifra/`), keeping dev stubs byte-identical to production's. */
export function renderBoundaryPluginModule(): string {
  return `// Generated by \`nifra dev --bun\` - do not edit. Regenerated on every dev start.
import { serverFnStubPlugin, serverOnlyEmptyPlugin } from "@nifrajs/web/build"

const fn = serverFnStubPlugin()
const serverOnly = serverOnlyEmptyPlugin()

export default {
  name: "nifra-dev-boundary",
  setup(build) {
    serverOnly.setup(build)
    fn.setup(build)
  },
}
`
}

export interface BunDevConfig {
  readonly bunfigPath: string
}

/** Write the generated config for an app; returns the bunfig path to re-exec with. */
export async function writeBunDevConfig(appRoot: string): Promise<BunDevConfig> {
  const dir = resolve(appRoot, ".nifra", "dev-bun")
  mkdirSync(dir, { recursive: true })
  const pluginPath = resolve(dir, "boundary-plugin.ts")
  writeFileSync(pluginPath, renderBoundaryPluginModule())
  const userToml = await Bun.file(resolve(appRoot, "bunfig.toml"))
    .text()
    .catch(() => undefined)
  const bunfigPath = resolve(dir, "bunfig.toml")
  writeFileSync(bunfigPath, renderDevBunfig(pluginPath, userBunfigSlice(userToml), appRoot))
  return { bunfigPath }
}
