/** Deterministic, dependency-free SDK generation from the backend's OpenAPI contract. */
import { existsSync } from "node:fs"
import { basename, resolve } from "node:path"
import { type OpenAPIDocument, toOpenAPI } from "@nifrajs/schema/openapi"

export type SdkLanguage = "python" | "go"

interface OperationLike {
  readonly operationId?: string
  readonly parameters?: readonly {
    readonly name: string
    readonly in: "path" | "query"
    readonly required: boolean
  }[]
  readonly requestBody?: unknown
}

const HTTP_METHODS = ["get", "post", "put", "patch", "delete", "head", "options"] as const

function operations(
  document: OpenAPIDocument,
): readonly { method: string; path: string; operation: OperationLike }[] {
  const result: { method: string; path: string; operation: OperationLike }[] = []
  for (const [path, item] of Object.entries(document.paths).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    for (const method of HTTP_METHODS) {
      const operation = (item as Record<string, unknown>)[method]
      if (operation !== null && typeof operation === "object") {
        result.push({ method, path, operation: operation as OperationLike })
      }
    }
  }
  return result
}

function identifier(value: string, fallback: string): string {
  const startsWithDigit = /^\d/.test(value)
  const normalized = value
    .replace(/[^A-Za-z0-9_]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/^_+|_+$/g, "")
  const safe = startsWithDigit ? `_${normalized}` : normalized
  return safe === "" || safe === "_" ? fallback : safe
}

function operationName(operation: OperationLike, method: string, path: string): string {
  return identifier(operation.operationId ?? `${method}_${path}`, `${method}_request`)
}

function uniqueNames(items: readonly string[]): readonly string[] {
  const counts = new Map<string, number>()
  return items.map((item) => {
    const count = (counts.get(item) ?? 0) + 1
    counts.set(item, count)
    return count === 1 ? item : `${item}_${count}`
  })
}

function pathParameters(path: string): readonly string[] {
  return [...path.matchAll(/\{([^}]+)\}/g)].map((match) => match[1]!).filter(Boolean)
}

function pythonSdk(document: OpenAPIDocument): string {
  const entries = operations(document)
  const names = uniqueNames(
    entries.map(({ method, path, operation }) => operationName(operation, method, path)),
  )
  const methods: string[] = []
  entries.forEach(({ method, path, operation }, index) => {
    const name = names[index]!
    const pathParams = pathParameters(path)
    const queryParams = (operation.parameters ?? []).filter((parameter) => parameter.in === "query")
    const used = new Set(["self", "body", ...pathParams])
    const queryNames = queryParams.map((parameter) => {
      let value = identifier(parameter.name, "query")
      while (used.has(value)) value += "_"
      used.add(value)
      return value
    })
    const args = pathParams.map((parameter) => `${identifier(parameter, "param")}: Any`)
    const keywordArgs = queryParams.map((parameter, queryIndex) => {
      const required = parameter.required ? "" : " = None"
      return `${queryNames[queryIndex]!}: Any${required}`
    })
    if (operation.requestBody !== undefined) keywordArgs.push("body: Any = None")
    const signature = [...args, ...(keywordArgs.length > 0 ? ["*", ...keywordArgs] : [])].join(", ")
    const query =
      queryNames.length === 0
        ? "None"
        : `{${queryNames.map((value) => `${JSON.stringify(value)}: ${value}`).join(", ")}}`
    const paths =
      pathParams.length === 0
        ? "None"
        : `{${pathParams.map((value) => `${JSON.stringify(value)}: ${identifier(value, "param")}`).join(", ")}}`
    const body = operation.requestBody === undefined ? "None" : "body"
    methods.push(
      `    def ${name}(self${signature ? `, ${signature}` : ""}) -> Any:\n` +
        `        return self._request(${JSON.stringify(method.toUpperCase())}, ${JSON.stringify(path)}, path_params=${paths}, query=${query}, body=${body})`,
    )
  })
  return `# Generated by nifra. Regenerate with: nifra sdk --lang python
from __future__ import annotations

import json
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Mapping


class NifraApiError(RuntimeError):
    def __init__(self, status: int, body: Any):
        super().__init__(f"Nifra API request failed with HTTP {status}")
        self.status = status
        self.body = body


class Client:
    def __init__(self, base_url: str, headers: Mapping[str, str] | None = None, timeout: float = 30.0):
        self.base_url = base_url.rstrip("/")
        self.headers = dict(headers or {})
        self.timeout = timeout

    def _request(self, method: str, path: str, *, path_params: Mapping[str, Any] | None, query: Mapping[str, Any] | None, body: Any) -> Any:
        route = path
        for key, value in (path_params or {}).items():
            route = route.replace("{" + key + "}", urllib.parse.quote(str(value), safe=""))
        params = [(key, value) for key, value in (query or {}).items() if value is not None]
        url = self.base_url + route
        if params:
            url += ("&" if "?" in url else "?") + urllib.parse.urlencode(params, doseq=True)
        payload = None if body is None else json.dumps(body).encode("utf-8")
        request = urllib.request.Request(url, data=payload, method=method, headers=self.headers)
        if payload is not None:
            request.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                raw = response.read()
                return json.loads(raw) if raw else None
        except urllib.error.HTTPError as error:
            raw = error.read()
            try:
                value = json.loads(raw) if raw else None
            except json.JSONDecodeError:
                value = raw.decode("utf-8", errors="replace")
            raise NifraApiError(error.code, value) from error

${methods.length === 0 ? "    pass" : methods.join("\n\n")}
`
}

function goExportName(value: string): string {
  const name = identifier(value, "Request")
  return name[0]!.toUpperCase() + name.slice(1)
}

function goSdk(document: OpenAPIDocument): string {
  const entries = operations(document)
  const names = uniqueNames(
    entries.map(({ method, path, operation }) => operationName(operation, method, path)),
  )
  const methods: string[] = []
  entries.forEach(({ method, path }, index) => {
    const pathParams = pathParameters(path)
    const args = pathParams.map((parameter) => `${identifier(parameter, "param")} string`)
    args.push("query url.Values", "body any")
    const pathMap =
      pathParams.length === 0
        ? "nil"
        : `map[string]string{${pathParams.map((value) => `${JSON.stringify(value)}: ${identifier(value, "param")}`).join(", ")}}`
    methods.push(
      `func (c *Client) ${goExportName(names[index]!)}(${args.join(", ")}) (any, error) {\n` +
        `    return c.request(http.Method${method[0]!.toUpperCase()}${method.slice(1)}, ${JSON.stringify(path)}, ${pathMap}, query, body)\n` +
        `}`,
    )
  })
  return `// Code generated by nifra. Regenerate with: nifra sdk --lang go
package nifrasdk

import (
    "bytes"
    "encoding/json"
    "fmt"
    "io"
    "net/http"
    "net/url"
    "strings"
)

type Client struct {
    BaseURL string
    HTTP *http.Client
    Headers http.Header
}

func NewClient(baseURL string) *Client {
    return &Client{BaseURL: strings.TrimRight(baseURL, "/"), HTTP: http.DefaultClient, Headers: make(http.Header)}
}

func (c *Client) request(method, path string, pathParams map[string]string, query url.Values, body any) (any, error) {
    route := path
    for key, value := range pathParams {
        route = strings.ReplaceAll(route, "{"+key+"}", url.PathEscape(value))
    }
    target := c.BaseURL + route
    parsed, err := url.Parse(target)
    if err != nil { return nil, err }
    parsed.RawQuery = query.Encode()
    var reader io.Reader
    if body != nil {
        payload, err := json.Marshal(body)
        if err != nil { return nil, err }
        reader = bytes.NewReader(payload)
    }
    request, err := http.NewRequest(method, parsed.String(), reader)
    if err != nil { return nil, err }
    for key, values := range c.Headers { for _, value := range values { request.Header.Add(key, value) } }
    if body != nil { request.Header.Set("Content-Type", "application/json") }
    response, err := c.HTTP.Do(request)
    if err != nil { return nil, err }
    defer response.Body.Close()
    raw, err := io.ReadAll(response.Body)
    if err != nil { return nil, err }
    var value any
    if len(raw) > 0 { if err := json.Unmarshal(raw, &value); err != nil { value = string(raw) } }
    if response.StatusCode < 200 || response.StatusCode >= 300 { return nil, fmt.Errorf("nifra API request failed with HTTP %d: %v", response.StatusCode, value) }
    return value, nil
}

${methods.length === 0 ? "// No operations were found.\n" : `${methods.join("\n\n")}\n`}`
}

/** Render a generated SDK. Python uses the standard library; Go uses net/http. */
export function renderSdk(document: OpenAPIDocument, language: SdkLanguage): string {
  return language === "python" ? pythonSdk(document) : goSdk(document)
}

/** Load `backend.ts`, generate an SDK, and write it to the project. */
export async function runSdk(
  cwd: string,
  options: { readonly language: SdkLanguage; readonly out?: string },
): Promise<void> {
  const backendPath = resolve(cwd, "backend.ts")
  if (!existsSync(backendPath)) {
    throw new Error(`[nifra] no backend.ts in ${cwd} - SDK generation needs the API contract.`)
  }
  const backend = ((await import(backendPath)) as { backend?: unknown }).backend
  if (backend === undefined) throw new Error(`[nifra] ${backendPath} does not export \`backend\`.`)
  const document = toOpenAPI(backend as Parameters<typeof toOpenAPI>[0], {
    title: `${basename(cwd)} API`,
    version: "1.0.0",
  })
  const extension = options.language === "python" ? "py" : "go"
  const out = resolve(cwd, options.out ?? `nifra_sdk.${extension}`)
  await Bun.write(out, renderSdk(document, options.language))
  console.log(
    `[nifra] wrote ${options.language} SDK with ${Object.keys(document.paths).length} path${Object.keys(document.paths).length === 1 ? "" : "s"} to ${out}`,
  )
}
