/**
 * `nifra sync-manifest` - regenerate a committed web `server-manifest.ts` from the current `routes/` tree
 * WITHOUT a full build. The manifest is a generated file that bakes the route table (+ client-asset hashes)
 * for a disk-less edge worker; after adding/renaming/removing a route it drifts, and `nifra check` flags it.
 * Regenerating it used to require the whole `build` (server + worker + migrate bundles). This re-scans
 * `routes/` and rewrites just the manifest's route table, preserving the baked client-asset references.
 *
 * It does NOT rebuild the client bundle: a brand-new HYDRATING route still needs a full build so its client
 * chunk exists. This clears route-table drift for the common case (a loader edit, an SSR-only route, a
 * rename) in milliseconds, and prints that caveat for the case it can't cover.
 */

import { join } from "node:path"
import { Glob } from "bun"
import { codeUnitOrder } from "./internal/code-unit-order.ts"

// The marker `generateServerManifest` writes at the top of the file - so a user file merely named
// `server-manifest.ts` is never mistaken for a generated one. Mirrors `nifra check`'s drift scan.
const GENERATED_MARKER = "GENERATED by @nifrajs/web generateServerManifest"
// The first route-import specifier's prefix up to `routes/` (`./`, `../`, `./src/`, …) - locates the
// routes dir relative to the manifest and strips imports to route-relative keys.
const ROUTES_PREFIX = /["'](\.{1,2}(?:\/[^"'/]+)*?\/routes\/)[^"']+["']/
const IGNORED = /(^|\/)(node_modules|dist(-[a-z0-9]+)?|build|\.nifra|\.git|\.wrangler|coverage)\//
// The fs codes that mean the routes dir is absent or unreadable. Every other throw is the route table
// refusing to build, which must fail the command rather than read as "no manifest found".
const ROUTES_DIR_UNAVAILABLE = new Set(["ENOENT", "ENOTDIR", "EACCES", "EPERM"])

function routesDirUnavailable(error: unknown): boolean {
  if (typeof error !== "object" || error === null || !("code" in error)) return false
  return typeof error.code === "string" && ROUTES_DIR_UNAVAILABLE.has(error.code)
}

export interface SyncManifestResult {
  /** The committed server-manifest file (relative to cwd). */
  readonly file: string
  /** True when the file's route table changed and it was rewritten. */
  readonly changed: boolean
  /** Route files now imported that weren't before (added). */
  readonly added: readonly string[]
  /** Route files no longer imported (removed/renamed away). */
  readonly removed: readonly string[]
  /** Set when the sync was REFUSED because discovery found zero routes for a manifest that had some
   * (`routes/` likely emptied by mistake) - the manifest was left untouched rather than wiped. */
  readonly refusedEmpty?: boolean
  /** Set when the `routes/` tree could not be built into a route table (a duplicate route, two routes of
   * one shape sharing a path, ...) - the manifest was left untouched and the sync failed. */
  readonly error?: string
}

/**
 * Discover every generated `server-manifest.ts` under `cwd` and re-sync its route table from the live
 * `routes/` tree, preserving baked client assets. Returns one result per generated manifest. Never throws
 * on a per-manifest failure: an absent or unreadable routes dir is skipped, and a route table that fails
 * to build is reported in that manifest's `error`.
 */
export async function syncServerManifests(cwd: string): Promise<SyncManifestResult[]> {
  const { discoverRoutes } = await import("@nifrajs/web/fs")
  const { parseManifestRouteFiles, diffManifestRoutes, resyncServerManifestSource } = await import(
    "@nifrajs/web/build"
  )
  const results: SyncManifestResult[] = []
  for await (const rawRel of new Glob("**/server-manifest.ts").scan({ cwd, dot: false })) {
    const rel = rawRel.replaceAll("\\", "/")
    if (IGNORED.test(rel)) continue
    const abs = join(cwd, rel)
    const source = await Bun.file(abs).text()
    if (!source.includes(GENERATED_MARKER)) continue // not a generated manifest - skip
    const routesPrefix = ROUTES_PREFIX.exec(source)?.[1]
    if (routesPrefix === undefined) continue // no routes/ imports -> nothing to sync
    const manifestDir = rel.includes("/") ? rel.slice(0, rel.lastIndexOf("/")) : ""
    const routesDir = join(cwd, manifestDir, routesPrefix)
    let next: string
    try {
      next = resyncServerManifestSource(source, discoverRoutes(routesDir), routesPrefix)
    } catch (error) {
      if (routesDirUnavailable(error)) continue // not a manifest we can sync
      const message = error instanceof Error ? error.message : String(error)
      results.push({ file: rel, changed: false, added: [], removed: [], error: message })
      continue
    }
    const before = parseManifestRouteFiles(source, routesPrefix)
    const after = parseManifestRouteFiles(next, routesPrefix)
    // Floor guard: refuse to overwrite a populated manifest with an empty one. Discovery yielding zero
    // routes for a manifest that had some means `routes/` was likely emptied by mistake - writing the wipe
    // would silently un-serve every route. Leave the file untouched and surface it instead.
    if (after.length === 0 && before.length > 0) {
      results.push({ file: rel, changed: false, added: [], removed: [], refusedEmpty: true })
      continue
    }
    const changed = next !== source
    if (changed) await Bun.write(abs, next)
    // `diff(before, after)`: `missing` = files now present (added), `extra` = files gone (removed).
    const drift = diffManifestRoutes(before, after)
    results.push({ file: rel, changed, added: drift.missing, removed: drift.extra })
  }
  return results.sort((a, b) => codeUnitOrder(a.file, b.file))
}

/** True when no manifest's route table failed to build. */
export function syncManifestsOk(results: readonly SyncManifestResult[]): boolean {
  return results.every((r) => r.error === undefined)
}

/** Per-file summary lines + the client-rebuild caveat. */
export function renderSyncManifestResults(results: readonly SyncManifestResult[]): string[] {
  if (results.length === 0)
    return ["nifra sync-manifest: no generated server-manifest.ts found under this directory."]
  const lines: string[] = []
  let anyChanged = false
  for (const r of results) {
    if (r.error !== undefined) {
      lines.push(
        `✖ ${r.file}: routes/ does not build a route table; left untouched.`,
        `    ${r.error}`,
      )
    } else if (r.refusedEmpty) {
      lines.push(
        `⚠ ${r.file}: refused - routes/ has zero routes but the manifest had some; left untouched (delete the manifest yourself if this is intentional).`,
      )
    } else if (r.changed) {
      anyChanged = true
      lines.push(`✓ synced ${r.file}`)
      if (r.added.length > 0) lines.push(`    added:   ${r.added.join(", ")}`)
      if (r.removed.length > 0) lines.push(`    removed: ${r.removed.join(", ")}`)
    } else {
      lines.push(`• ${r.file} already in sync`)
    }
  }
  if (anyChanged) {
    lines.push(
      "\nRe-synced the server manifest's route table. If you added or changed a HYDRATING route\n" +
        "component (not just a loader / SSR-only route), also run a full build so the client bundle matches.",
    )
  }
  return lines
}

/** CLI entry: sync every generated manifest and print the summary. False when a route table failed to build. */
export async function runSyncManifest(cwd: string): Promise<boolean> {
  const results = await syncServerManifests(cwd)
  console.log(renderSyncManifestResults(results).join("\n"))
  return syncManifestsOk(results)
}
