/**
 * `nifra sync-manifest` - regenerate a committed web `server-manifest.ts` from the current `routes/` tree
 * WITHOUT a full build. The manifest is a generated file that bakes the route table (+ client-asset hashes)
 * for a disk-less edge worker; after adding/renaming/removing a route it drifts, and `nifra check` flags it.
 * Regenerating it used to require the whole `build` (server + worker + migrate bundles). This re-scans
 * `routes/` and rewrites just the manifest's route table, preserving the baked client-asset references.
 *
 * It does NOT rebuild the client bundle: a brand-new HYDRATING route still needs a full build so its client
 * chunk exists. This clears route-table drift for the common case (a loader edit, an SSR-only route, a
 * rename) in milliseconds, and prints that caveat for the case it can't cover.
 */

import { join } from "node:path"
import { Glob } from "bun"

// The marker `generateServerManifest` writes at the top of the file - so a user file merely named
// `server-manifest.ts` is never mistaken for a generated one. Mirrors `nifra check`'s drift scan.
const GENERATED_MARKER = "GENERATED by @nifrajs/web generateServerManifest"
// The first route-import specifier's prefix up to `routes/` (`./`, `../`, `./src/`, …) - locates the
// routes dir relative to the manifest and strips imports to route-relative keys.
const ROUTES_PREFIX = /["'](\.{1,2}(?:\/[^"'/]+)*?\/routes\/)[^"']+["']/
const IGNORED = /(^|\/)(node_modules|dist(-[a-z0-9]+)?|build|\.nifra|\.git|\.wrangler|coverage)\//

export interface SyncManifestResult {
  /** The committed server-manifest file (relative to cwd). */
  readonly file: string
  /** True when the file's route table changed and it was rewritten. */
  readonly changed: boolean
  /** Route files now imported that weren't before (added). */
  readonly added: readonly string[]
  /** Route files no longer imported (removed/renamed away). */
  readonly removed: readonly string[]
}

/**
 * Discover every generated `server-manifest.ts` under `cwd` and re-sync its route table from the live
 * `routes/` tree, preserving baked client assets. Returns one result per generated manifest. Never throws
 * on a per-manifest miss (an unreadable/absent routes dir is skipped).
 */
export async function syncServerManifests(cwd: string): Promise<SyncManifestResult[]> {
  const { discoverRoutes } = await import("@nifrajs/web/fs")
  const { parseManifestRouteFiles, diffManifestRoutes, resyncServerManifestSource } = await import(
    "@nifrajs/web/build"
  )
  const results: SyncManifestResult[] = []
  for await (const rel of new Glob("**/server-manifest.ts").scan({ cwd, dot: false })) {
    if (IGNORED.test(rel)) continue
    const abs = join(cwd, rel)
    const source = await Bun.file(abs).text()
    if (!source.includes(GENERATED_MARKER)) continue // not a generated manifest - skip
    const routesPrefix = ROUTES_PREFIX.exec(source)?.[1]
    if (routesPrefix === undefined) continue // no routes/ imports -> nothing to sync
    const manifestDir = rel.includes("/") ? rel.slice(0, rel.lastIndexOf("/")) : ""
    const routesDir = join(cwd, manifestDir, routesPrefix)
    let next: string
    try {
      next = resyncServerManifestSource(source, discoverRoutes(routesDir), routesPrefix)
    } catch {
      continue // routes dir gone/unreadable - not a manifest we can sync
    }
    const changed = next !== source
    if (changed) await Bun.write(abs, next)
    // `diff(before, after)`: `missing` = files now present (added), `extra` = files gone (removed).
    const drift = diffManifestRoutes(
      parseManifestRouteFiles(source, routesPrefix),
      parseManifestRouteFiles(next, routesPrefix),
    )
    results.push({ file: rel, changed, added: drift.missing, removed: drift.extra })
  }
  return results.sort((a, b) => a.file.localeCompare(b.file))
}

/** CLI entry: sync every generated manifest, print a per-file summary + the client-rebuild caveat. */
export async function runSyncManifest(cwd: string): Promise<boolean> {
  const results = await syncServerManifests(cwd)
  if (results.length === 0) {
    console.log("nifra sync-manifest: no generated server-manifest.ts found under this directory.")
    return true
  }
  let anyChanged = false
  for (const r of results) {
    if (r.changed) {
      anyChanged = true
      console.log(`✓ synced ${r.file}`)
      if (r.added.length > 0) console.log(`    added:   ${r.added.join(", ")}`)
      if (r.removed.length > 0) console.log(`    removed: ${r.removed.join(", ")}`)
    } else {
      console.log(`• ${r.file} already in sync`)
    }
  }
  if (anyChanged) {
    console.log(
      "\nRe-synced the server manifest's route table. If you added or changed a HYDRATING route\n" +
        "component (not just a loader / SSR-only route), also run a full build so the client bundle matches.",
    )
  }
  return true
}
