/**
 * The starter's `.nifra/types`, written with the scaffold so `import type { Route } from "./+types/index"`
 * resolves before any nifra command has run. From the first `nifra dev|build|check|types` on, the
 * generator in `@nifrajs/web/route-types` owns the directory; `route-types.test.ts` holds this text
 * byte-equal to what that generator writes for every scaffold that has routes.
 */

/** The starter's route files: `[name, kind, has a backend half]`. */
const STARTER_ROUTES = [
  ["_404", "page", false],
  ["_layout", "layout", false],
  ["index", "page", true],
] as const

const header = (label: string): string =>
  `// Generated by nifra from ${label}. Do not edit: \`nifra types\` rewrites it.`

function routeModule(
  name: string,
  extension: string,
  kind: "page" | "layout",
  hasBackend: boolean,
): string {
  // Only a script module's exports are visible to TypeScript; a .svelte/.vue one is an ambient shim.
  const script = extension === "tsx"
  const lines = [
    header(`routes/${name}.${extension}`),
    '/// <reference path="../../register.d.ts" />',
    'import type { OutputOf, RouteLoaderArgs, SearchSchemaOf } from "@nifrajs/client"',
  ]
  if (kind === "page") lines.push('import type { RenderProps } from "@nifrajs/web"')
  lines.push("")
  if (hasBackend) lines.push(`type Backend = typeof import("../../../../routes/${name}.backend")`)
  if (script) lines.push(`type Frontend = typeof import("../../../../routes/${name}")`)
  if (hasBackend || script) lines.push("")
  const output = (schema: string): string =>
    hasBackend ? `OutputOf<Backend, "${schema}">` : "null"
  lines.push(
    "export namespace Route {",
    "  /** The URL params this route's path carries. */",
    "  export type Params = Record<string, never>",
    "  /** What the loader sends to the browser: the output type of `loaderOutput`. */",
    `  export type LoaderData = ${output("loaderOutput")}`,
    "  /** What the action sends back: the output type of `actionOutput`. */",
    `  export type ActionData = ${output("actionOutput")}`,
    "  /** The context the backend half's loader receives. */",
    `  export type LoaderArgs = RouteLoaderArgs<Params${script ? ", SearchSchemaOf<Frontend>" : ""}>`,
    "  /** The context the backend half's action receives. */",
    "  export type ActionArgs = LoaderArgs",
  )
  if (kind === "page") {
    lines.push(
      "  /** The page component's props. */",
      '  export type ComponentProps = Omit<RenderProps, "data" | "actionData" | "params"> & {',
      "    readonly data: LoaderData",
      "    readonly actionData?: ActionData",
      "    readonly params: Params",
      "  }",
    )
  } else {
    lines.push(
      "  /** The layout component's props; `Children` is the adapter's children type. */",
      "  export type ComponentProps<Children = unknown> = {",
      "    readonly data: LoaderData",
      "    readonly children?: Children",
      "  }",
    )
  }
  lines.push("}", "")
  return lines.join("\n")
}

/** Every `.nifra/types` file of a starter whose route files carry `extension`, by app-relative path. */
export function starterRouteTypes(extension: string): Map<string, string> {
  const files = new Map<string, string>()
  files.set(
    ".nifra/types/register.d.ts",
    [
      header("backend/app.ts"),
      'import type { backend } from "../../backend/app"',
      "",
      'declare module "@nifrajs/client" {',
      "  interface Register {",
      "    readonly backend: typeof backend",
      "  }",
      "}",
      "",
    ].join("\n"),
  )
  for (const [name, kind, hasBackend] of STARTER_ROUTES) {
    files.set(
      `.nifra/types/routes/+types/${name}.d.ts`,
      routeModule(name, extension, kind, hasBackend),
    )
  }
  return files
}
