#!/usr/bin/env bun
/**
 * Generate the type-only Node outcome contract consumed by @nifrajs/node.
 *
 * The Node adapter deliberately has no runtime dependency on @nifrajs/core. Keeping the outcome
 * contract generated from core preserves that deployment shape while making drift visible to the
 * adapter's own TypeScript build and to a checked-in --check gate.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import ts from "typescript"

const ROOT = resolve(import.meta.dir, "..")
const SOURCE = resolve(ROOT, "packages/core/src/server/node-outcome.ts")
const TARGET = resolve(ROOT, "packages/node/src/generated/node-outcome.ts")

export function generateNodeOutcomeContract(): string {
  const sourceText = readFileSync(SOURCE, "utf8")
  const source = ts.createSourceFile(
    SOURCE,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  )
  const declaration = source.statements.find(
    (statement): statement is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(statement) && statement.name.text === "NodeServeOutcome",
  )
  if (declaration === undefined) {
    throw new Error(`node outcome contract missing from ${SOURCE}`)
  }
  return [
    "// Generated by scripts/gen-node-outcome.ts - edit packages/core/src/server/node-outcome.ts instead.",
    "// This file is type-only so @nifrajs/node stays free of a runtime @nifrajs/core dependency.",
    "",
    `${declaration.getText(source)}\n`,
  ].join("\n")
}

if (import.meta.main) {
  const generated = generateNodeOutcomeContract()
  if (process.argv.includes("--check")) {
    const current = existsSync(TARGET) ? readFileSync(TARGET, "utf8") : ""
    if (current !== generated) {
      console.error(`✗ ${TARGET} is stale - run \`bun run gen:node-outcome\`.`)
      process.exit(1)
    }
    console.log("✓ @nifrajs/node outcome contract is current")
  } else {
    mkdirSync(resolve(TARGET, ".."), { recursive: true })
    writeFileSync(TARGET, generated)
    console.log("Generated @nifrajs/node outcome contract.")
  }
}
