#!/usr/bin/env bun
/**
 * Generate the type-only Node outcome contract consumed by @nifrajs/node.
 *
 * The Node adapter deliberately has no runtime dependency on @nifrajs/core. Keeping the outcome
 * contract generated from core preserves that deployment shape while making drift visible to the
 * adapter's own TypeScript build and to a checked-in --check gate.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { resolve } from "node:path"
import ts from "typescript"
import { runNodeOutcomeConformance } from "./node-outcome-conformance.ts"

const ROOT = resolve(import.meta.dir, "..")
const OUTCOME_SOURCE = resolve(ROOT, "packages/core/src/server/node-outcome.ts")
const OUTCOME_TARGET = resolve(ROOT, "packages/node/src/generated/node-outcome.ts")
const MARKERS_SOURCE = resolve(ROOT, "packages/core/src/server/bridge-markers.ts")
const MARKERS_TARGET = resolve(ROOT, "packages/node/src/generated/bridge-markers.ts")

function parse(sourcePath: string): ts.SourceFile {
  return ts.createSourceFile(
    sourcePath,
    readFileSync(sourcePath, "utf8"),
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TS,
  )
}

export function generateNodeOutcomeContract(): string {
  const source = parse(OUTCOME_SOURCE)
  const declaration = source.statements.find(
    (statement): statement is ts.TypeAliasDeclaration =>
      ts.isTypeAliasDeclaration(statement) && statement.name.text === "NodeServeOutcome",
  )
  if (declaration === undefined) {
    throw new Error(`node outcome contract missing from ${OUTCOME_SOURCE}`)
  }
  return [
    "// Generated by scripts/gen-node-outcome.ts - edit packages/core/src/server/node-outcome.ts instead.",
    "// This file is type-only so @nifrajs/node stays free of a runtime @nifrajs/core dependency.",
    "",
    `${declaration.getText(source)}\n`,
  ].join("\n")
}

/**
 * The wire marker keys, copied verbatim from core's single source. A runtime const rather than a type
 * (the strings ARE the protocol), but still no runtime dependency on core: the literals are inlined at
 * generation time exactly as the outcome type is.
 */
export function generateBridgeMarkers(): string {
  const source = parse(MARKERS_SOURCE)
  const declaration = source.statements.find(
    (statement): statement is ts.VariableStatement =>
      ts.isVariableStatement(statement) &&
      statement.declarationList.declarations.some(
        (decl) => ts.isIdentifier(decl.name) && decl.name.text === "NODE_BRIDGE_MARKER_KEYS",
      ),
  )
  if (declaration === undefined) {
    throw new Error(`NODE_BRIDGE_MARKER_KEYS missing from ${MARKERS_SOURCE}`)
  }
  return [
    "// Generated by scripts/gen-node-outcome.ts - edit packages/core/src/server/bridge-markers.ts instead.",
    "// The marker strings ARE the wire protocol; copied here so @nifrajs/node reads the identical keys",
    "// without a runtime dependency on @nifrajs/core.",
    "",
    `${declaration.getText(source)}\n`,
  ].join("\n")
}

const ARTIFACTS: readonly { readonly target: string; readonly render: () => string }[] = [
  { target: OUTCOME_TARGET, render: generateNodeOutcomeContract },
  { target: MARKERS_TARGET, render: generateBridgeMarkers },
]

if (import.meta.main) {
  const check = process.argv.includes("--check")
  for (const { target, render } of ARTIFACTS) {
    const generated = render()
    if (check) {
      const current = existsSync(target) ? readFileSync(target, "utf8") : ""
      if (current !== generated) {
        console.error(`✗ ${target} is stale - run \`bun run gen:node-outcome\`.`)
        process.exit(1)
      }
    } else {
      mkdirSync(resolve(target, ".."), { recursive: true })
      writeFileSync(target, generated)
    }
  }
  if (check) {
    await runNodeOutcomeConformance()
    console.log("✓ @nifrajs/node outcome contract is current")
  } else {
    console.log("Generated @nifrajs/node outcome contract + bridge markers.")
  }
}
