import { inProcessClient } from "@nifrajs/client"
import { createWebApp } from "@nifrajs/web"
import { solidAdapter } from "@nifrajs/web-solid"
import { backend } from "./backend"
// Generated by build.ts (buildServer) — the static-import route manifest + baked client entry URL.
import { clientEntry, manifest } from "./server-manifest"

/** The nifra app — identical across every runtime. Only the entry that wraps it differs. (Solid.) */
export const app = createWebApp({
  adapter: solidAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra — portable SSR (Solid)",
})
