/**
 * Node's built-in module names without the `node:` prefix (`fs`, `fs/promises`, ...), for the client
 * build guards. A fixed list rather than `module.builtinModules`, which differs between Node and Bun
 * (Bun adds `bun:*`), so a leak reads the same whichever runtime runs the build. Names that exist only
 * with the prefix (`node:test`, `node:sqlite`) are covered by the prefix itself.
 */
const NODE_BUILTIN_MODULES: ReadonlySet<string> = new Set([
  "_http_agent",
  "_http_client",
  "_http_common",
  "_http_incoming",
  "_http_outgoing",
  "_http_server",
  "_stream_duplex",
  "_stream_passthrough",
  "_stream_readable",
  "_stream_transform",
  "_stream_wrap",
  "_stream_writable",
  "_tls_common",
  "_tls_wrap",
  "assert",
  "assert/strict",
  "async_hooks",
  "buffer",
  "child_process",
  "cluster",
  "console",
  "constants",
  "crypto",
  "dgram",
  "diagnostics_channel",
  "dns",
  "dns/promises",
  "domain",
  "events",
  "fs",
  "fs/promises",
  "http",
  "http2",
  "https",
  "inspector",
  "inspector/promises",
  "module",
  "net",
  "os",
  "path",
  "path/posix",
  "path/win32",
  "perf_hooks",
  "process",
  "punycode",
  "querystring",
  "readline",
  "readline/promises",
  "repl",
  "stream",
  "stream/consumers",
  "stream/promises",
  "stream/web",
  "string_decoder",
  "sys",
  "timers",
  "timers/promises",
  "tls",
  "trace_events",
  "tty",
  "url",
  "util",
  "util/types",
  "v8",
  "vm",
  "wasi",
  "worker_threads",
  "zlib",
])

/** Whether `specifier` names a Node built-in without the `node:` prefix (`fs/promises`). */
export const isBareNodeBuiltin = (specifier: string): boolean => NODE_BUILTIN_MODULES.has(specifier)
