/**
 * Turning a `*.fn.ts` module into the client stubs that call it.
 *
 * The server half of a server function must never reach a browser: it closes over database handles,
 * secrets and everything else the module imports. So the CLIENT build does not bundle these modules at
 * all - it replaces each one with a stub per export that POSTs to the route the server mounted.
 *
 * Pure on purpose. The Bun and Vite pipelines both need this transform and must produce byte-identical
 * stubs, so the generation lives here and each bundler contributes only its own plugin shell. A
 * divergence between the two would be a client that works in dev and 404s in production.
 *
 * ## Why the source is scanned rather than imported
 *
 * Reading the exports by importing the module would execute it, which is precisely what must not
 * happen in a client build. So the declarations are found textually, and the form is fixed:
 *
 *     export const addTodo = serverFn({ … }, async (input, c) => { … })
 *
 * Anything else is refused rather than skipped. A server function the scanner cannot see would simply
 * be absent from the client, and the failure would surface as `addTodo is not a function` at runtime,
 * far from the cause.
 */

/** Modules whose exports become client stubs. Mirrors the `*.server` convention's shape. */
export const SERVER_FN_MODULE = /\.fn(\.[cm]?[jt]sx?)?$/

/** `export const NAME = serverFn(` at the start of a line - the one declaration form. */
const DECLARATION = /^[\t ]*export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*serverFn\s*\(/gm
/** Any mention of `serverFn(` as a call, used to prove nothing was missed. */
const ANY_CALL = /\bserverFn\s*\(/g
/** Line comments and block comments, stripped before scanning so prose cannot register as code. */
const COMMENTS = /\/\*[\s\S]*?\*\/|(^|[^:])\/\/.*$/gm

/**
 * The namespace a `*.fn.ts` module is mounted under: its filename without the `.fn` suffix.
 *
 * Deriving it from the filename rather than the full path keeps the build machine's directory layout
 * out of a public URL, and keeps the route readable in logs. It also means the mount on the server -
 * `serverFunctions("todos", …)` - has to use the same word, which is the one thing a reader must check
 * by eye today; {@link SERVER_FN_MODULE} files are named for it precisely to make that obvious.
 */
export function serverFnNamespace(filePath: string): string {
  const base = filePath.replaceAll("\\", "/").split("/").pop() ?? ""
  return base.replace(SERVER_FN_MODULE, "")
}

/** The server functions a module declares, in source order. */
export function scanServerFnExports(source: string): string[] {
  const code = source.replaceAll(COMMENTS, "$1")
  const names = [...code.matchAll(DECLARATION)].map((m) => m[1] as string)
  const calls = [...code.matchAll(ANY_CALL)].length
  if (calls > names.length) {
    throw new Error(
      "[nifra/fn] a server function is declared in a form the client transform cannot read. Use " +
        "`export const name = serverFn(…)` at the top level: the client build scans the source rather " +
        "than importing it (importing would run your server code during a browser build), so a " +
        "declaration it cannot see would be missing from the client and fail as `name is not a function`.",
    )
  }
  return names
}

/**
 * The client replacement for a `*.fn.ts` module: one stub per export, and none of the original code.
 *
 * `credentials: "same-origin"` is explicit rather than relied upon - the server refuses a cross-origin
 * call, and stating it here means the browser never sends cookies somewhere that would reject them.
 * The content type is not decoration either: it is what makes a cross-origin form unable to forge one
 * of these calls, so the stub and the server guard have to agree on it.
 */
export function generateServerFnStub(source: string, namespace: string): string {
  const names = scanServerFnExports(source)
  const calls = names
    .map((name) => `export const ${name} = (input) => __nifraCall(${JSON.stringify(name)}, input)`)
    .join("\n")
  return `// Generated by @nifrajs/web: the server half of this module never reaches the browser.
const __nifraBase = ${JSON.stringify(`/_nifra/fn/${namespace}`)}

async function __nifraCall(name, input) {
  const response = await fetch(\`\${__nifraBase}/\${name}\`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(input === undefined ? {} : input),
    credentials: "same-origin",
  })
  if (response.status === 404) {
    throw new Error(
      \`[nifra/fn] \${name} is not mounted at \${__nifraBase}. The client derives that path from this \` +
        \`file's name, so the server's serverFunctions(...) namespace has to match it.\`,
    )
  }
  if (!response.ok) {
    let detail = ""
    try {
      detail = JSON.stringify(await response.json())
    } catch {
      // A non-JSON error body is not worth a second failure; the status carries enough.
    }
    throw new Error(\`[nifra/fn] \${name} failed: \${response.status}\${detail ? \` \${detail}\` : ""}\`)
  }
  return response.status === 204 ? undefined : await response.json()
}

${calls}
`
}
