/**
 * The `.server` convention, owned in one place.
 *
 * Four things need to agree on what a server-only module IS: the Bun client build, the Vite client
 * build, the Vite dev server, and `nifra dev --bun`'s refusal (which cannot transform, so it must
 * refuse instead). When each re-encoded the rule, they drifted - a hand-written glob
 * `**\/*.server.{ts,tsx,js,jsx,...}` missed the extensionless `db.server` that the regex matches, which
 * is a module the build empties and the guard waves through.
 *
 * A matcher that decides whether secrets reach a browser gets exactly one definition.
 */

/** Matches `db.server.ts`, `auth.server.tsx`, `x.server.mjs`, and the extensionless `foo.server`. */
export const SERVER_ONLY_MODULE = /\.server(\.[cm]?[jt]sx?)?$/

/**
 * The replacement body for an emptied module. A Proxy rather than `export {}` so any named OR default
 * import resolves to `undefined` instead of failing the bundle with a missing-export error - the client
 * degrades at the call site it wrote, not at link time in a file it never named.
 *
 * Shared so the Bun and Vite pipelines emit the same bytes; a parity test asserts it.
 */
export const SERVER_ONLY_REPLACEMENT = "module.exports = new Proxy({}, { get: () => undefined })"

const EXPORTED_DECLARATION =
  /\bexport\s+(?:declare\s+)?(?:async\s+)?(?:const|let|var|function|class|enum)\s+([A-Za-z_$][\w$]*)/g
const EXPORTED_LIST = /\bexport\s*\{([^}]*)\}(?:\s*from\s*["'][^"']+["'])?/g

/**
 * Vite dev serves native ESM, so the Bun/CommonJS proxy above is invalid there. Emit inert ESM
 * bindings derived from the source's public names while discarding the implementation and imports.
 * An unsupported exotic export fails closed at ESM link time; server code is never served as fallback.
 */
export function viteServerOnlyReplacement(source: string): string {
  const names = new Set<string>()
  let hasDefault = /\bexport\s+default\b/.test(source)

  for (const match of source.matchAll(EXPORTED_DECLARATION)) names.add(match[1] as string)
  for (const match of source.matchAll(EXPORTED_LIST)) {
    for (const raw of (match[1] ?? "").split(",")) {
      const item = raw.trim().replace(/^type\s+/, "")
      if (item === "") continue
      const parts = item.split(/\s+as\s+/)
      const exported = (parts[1] ?? parts[0] ?? "").trim()
      if (exported === "default") hasDefault = true
      else if (/^[A-Za-z_$][\w$]*$/.test(exported)) names.add(exported)
    }
  }

  const bindings = [...names].sort().map((name) => `export const ${name} = undefined`)
  if (hasDefault) bindings.push("export default undefined")
  return `// Generated by @nifrajs/web: server-only implementation removed from the browser.\n${bindings.join("\n")}\n`
}
