/**
 * Repeatable REALISTIC-shape HTTP-benchmark aggregator - mirrors bench/http/aggregate.ts exactly,
 * pointed at bench/http-realworld/run.ts. Runs the full matrix N times in fresh subprocesses, takes
 * the median across runs for every framework × workload cell, and writes the results table to
 * BENCHMARKS-REALWORLD.md (gitignored, same convention as BENCHMARKS.md).
 *
 *   bun run bench/http-realworld/aggregate.ts                  # 3 runs, print tables to stdout
 *   bun run bench/http-realworld/aggregate.ts --runs 7 --write # 7 runs, write BENCHMARKS-REALWORLD.md
 *   bun run bench/http-realworld/aggregate.ts node --runs 3    # one section only
 */
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { httpRealworldFromResults, writeSiteBench } from "../site-bench.ts"

const HERE = dirname(fileURLToPath(import.meta.url))
const RUN = join(HERE, "run.ts")
const OUT = join(HERE, "..", "..", "BENCHMARKS-REALWORLD.md")

const TEMPLATE = `# Realistic-shape benchmarks - local results (not committed)

The bare-route matrix ([BENCHMARKS.md](./BENCHMARKS.md)) measures the framework floor and is what
nifra's fused Web lane (bare/query/body-only routes) targets. This suite measures the SAME GET/POST
split, but on a route with what a real API route actually has: security headers, CORS, a request-id
hook, bearer-token auth via a derive, and a cookie read. On nifra, that combination disqualifies the
route from every fused lane - it always takes the general lifecycle path. Compare the SAME
framework's ratio across both files to see the fused-lane premium directly, instead of assuming the
bare-route ratio generalizes to a real endpoint.

The third workload (the \`*-body\` rows) adds ONE body-observing middleware to the same GET - an
x-body-hash header over the final serialized body - via each framework's own idiomatic body tier:
nifra's \`onResponseBody\`, Fastify's \`onSend\`, Elysia's \`mapResponse\`, Hono's drain-and-rebuild
middleware, Express's \`res.json\` wrap, and inline hashing for the raw ceilings. The delta against
the plain GET row is what each framework charges middleware to SEE the response body.

Generated by \`bun run bench:http:realworld:update\`. See [bench/README.md](bench/README.md).

<!-- BENCH:META:START -->
<!-- BENCH:META:END -->

## bun

<!-- BENCH:bun:START -->
<!-- BENCH:bun:END -->

## node

<!-- BENCH:node:START -->
<!-- BENCH:node:END -->

## deno

<!-- BENCH:deno:START -->
<!-- BENCH:deno:END -->
`

interface Measure {
  readonly rps: number
  readonly p50ms: number
  readonly p99ms: number
}
interface Meta {
  readonly bun: string
  readonly node: string
  readonly deno: string
  readonly oha: string
  readonly runs: number
  readonly durationS: number
  readonly connections: number
}
type Results = Record<string, Record<string, Record<string, Measure>>>

// The body-hash workload is served by the `*-body` targets (same route + one body-observing
// middleware, each framework's own idiomatic tier); its rows and ceiling carry the `-body` suffix.
const BODY_WORKLOAD = "GET /api/orders (auth + middleware + body-hash)"
const WORKLOADS: readonly string[] = [
  "GET /api/orders (auth + 3 middleware)",
  "POST /api/orders (auth + 3 middleware)",
  BODY_WORKLOAD,
]
const FRAMEWORKS: Record<string, readonly string[]> = {
  bun: ["nifra", "elysia", "hono", "bun-native"],
  node: ["nifra", "hono", "fastify", "express", "elysia", "node-raw"],
  deno: ["nifra", "hono", "elysia", "deno-raw"],
}
const CEILING: Record<string, string> = {
  bun: "bun-native",
  node: "node-raw",
  deno: "deno-raw",
}

function rowNames(runtime: string, workload: string): readonly string[] {
  const base = FRAMEWORKS[runtime] ?? []
  return workload === BODY_WORKLOAD ? base.map((f) => `${f}-body`) : base
}

function ceilingName(runtime: string, workload: string): string {
  const base = CEILING[runtime] ?? ""
  return workload === BODY_WORKLOAD ? `${base}-body` : base
}

function parseArgs(argv: readonly string[]): { runtime?: string; runs: number; write: boolean } {
  const write = argv.includes("--write")
  const runsIdx = argv.indexOf("--runs")
  const runsRaw = runsIdx >= 0 ? argv[runsIdx + 1] : undefined
  const runs = runsRaw !== undefined && /^\d+$/.test(runsRaw) ? Number(runsRaw) : 3
  const runtime = argv.find((a, i) => !a.startsWith("--") && argv[i - 1] !== "--runs")
  return runtime !== undefined ? { runtime, runs, write } : { runs, write }
}

function median(nums: number[]): number {
  if (nums.length === 0) return 0
  const sorted = [...nums].sort((a, b) => a - b)
  return sorted[sorted.length >> 1] ?? 0
}

async function runOnce(runtime: string | undefined): Promise<{ meta: Meta; results: Results }> {
  const args = ["run", RUN]
  if (runtime !== undefined) args.push(runtime)
  args.push("--json")
  const proc = Bun.spawn(["bun", ...args], { stdout: "pipe", stderr: "inherit" })
  const [out, code] = await Promise.all([new Response(proc.stdout).text(), proc.exited])
  if (code !== 0) throw new Error(`run.ts exited ${code}`)
  const line = out.trim().split("\n").filter(Boolean).at(-1) ?? ""
  return JSON.parse(line) as { meta: Meta; results: Results }
}

function fmt(n: number): string {
  return Math.round(n).toLocaleString("en-US")
}

function table(runtime: string, workload: string, cells: Record<string, Measure>): string {
  const ceilRps = cells[ceilingName(runtime, workload)]?.rps ?? 0
  const rows = rowNames(runtime, workload)
    .map((f) => ({ f, m: cells[f] ?? { rps: 0, p50ms: 0, p99ms: 0 } }))
    .filter((r) => r.m.rps > 0)
    .sort((a, b) => b.m.rps - a.m.rps)
  const head = `| \`${workload}\` | req/s | p50 | p99 | % of ceiling |\n| --- | ---: | ---: | ---: | ---: |`
  const body = rows
    .map(({ f, m }) => {
      const pct = ceilRps > 0 ? `${Math.round((m.rps / ceilRps) * 100)}%` : "-"
      const cellVals = [
        f,
        `${fmt(m.rps)}`,
        `${m.p50ms.toFixed(2)}ms`,
        `${m.p99ms.toFixed(2)}ms`,
        pct,
      ]
      const cells2 = f.startsWith("nifra") ? cellVals.map((c) => `**${c}**`) : cellVals
      return `| ${cells2.join(" | ")} |`
    })
    .join("\n")
  return `${head}\n${body}`
}

function sectionBlock(runtime: string, results: Results): string {
  const cellsFor = (w: string): Record<string, Measure> => {
    const out: Record<string, Measure> = {}
    for (const f of Object.keys(results[runtime] ?? {})) {
      const m = results[runtime]?.[f]?.[w]
      if (m) out[f] = m
    }
    return out
  }
  const tables = WORKLOADS.map((w) => table(runtime, w, cellsFor(w))).join("\n\n")
  if (runtime !== "bun") return tables
  const ratio = (w: string): string => {
    const suffix = w === BODY_WORKLOAD ? "-body" : ""
    const nifra = results.bun?.[`nifra${suffix}`]?.[w]?.rps ?? 0
    const elysia = results.bun?.[`elysia${suffix}`]?.[w]?.rps ?? 0
    return nifra > 0 && elysia > 0 ? `${Math.round((nifra / elysia) * 100)}%` : "-"
  }
  const ratios = WORKLOADS.map((w) => `**${ratio(w)}** (\`${w}\`)`).join(", ")
  return `${tables}\n\nnifra vs Elysia (median): ${ratios}.`
}

function splice(doc: string, marker: string, content: string): string {
  const start = `<!-- BENCH:${marker}:START -->`
  const end = `<!-- BENCH:${marker}:END -->`
  const s = doc.indexOf(start)
  const e = doc.indexOf(end)
  if (s < 0 || e < 0 || e < s) {
    throw new Error(`BENCHMARKS-REALWORLD.md is missing the ${start} / ${end} markers`)
  }
  return `${doc.slice(0, s + start.length)}\n${content}\n${doc.slice(e)}`
}

const { runtime, runs, write } = parseArgs(process.argv.slice(2))
const runtimes = runtime ? [runtime] : ["bun", "node", "deno"]

const samples: Results[] = []
let meta: Meta | undefined
for (let i = 0; i < runs; i++) {
  process.stderr.write(`run ${i + 1}/${runs}…\n`)
  const { meta: m, results } = await runOnce(runtime)
  meta ??= m
  samples.push(results)
}
if (meta === undefined) throw new Error("no successful runs")

const merged: Results = {}
for (const rt of runtimes) {
  merged[rt] = {}
  const frameworks = new Set<string>()
  for (const s of samples) for (const f of Object.keys(s[rt] ?? {})) frameworks.add(f)
  for (const f of frameworks) {
    const wl: Record<string, Measure> = {}
    for (const w of WORKLOADS) {
      const got = samples.map((s) => s[rt]?.[f]?.[w]).filter((m): m is Measure => m !== undefined)
      if (got.length > 0) {
        wl[w] = {
          rps: median(got.map((m) => m.rps)),
          p50ms: median(got.map((m) => m.p50ms)),
          p99ms: median(got.map((m) => m.p99ms)),
        }
      }
    }
    ;(merged[rt] as Record<string, Record<string, Measure>>)[f] = wl
  }
}

const metaLine = `_Median of **${runs}** full-matrix runs (each a median of ${meta.runs} × ${meta.durationS}s oha samples @ ${meta.connections} connections) · Bun ${meta.bun} · Node ${meta.node} · Deno ${meta.deno} · oha ${meta.oha}. Read the same-run ratios, not the absolutes._`

if (!write) {
  console.log(`\n${metaLine}\n`)
  for (const rt of runtimes) console.log(`### ${rt}\n\n${sectionBlock(rt, merged)}\n`)
  process.exit(0)
}

// Publish the realistic slice alongside the bare one. A single-runtime run must not erase the
// other runtime tables in the canonical dataset, so this only writes when all three ran - the same
// discipline bench/http/aggregate.ts applies to `httpWorkloads`.
const realworld = httpRealworldFromResults(merged as never, {
  get: WORKLOADS[0] as string,
  post: WORKLOADS[1] as string,
  body: BODY_WORKLOAD,
})
if (runtimes.length === 3 && realworld.length === 3) {
  await writeSiteBench({ httpRealworld: realworld })
}

const benchFile = Bun.file(OUT)
let doc = (await benchFile.exists()) ? await benchFile.text() : TEMPLATE
doc = splice(doc, "META", metaLine)
for (const rt of runtimes) doc = splice(doc, rt, sectionBlock(rt, merged))
await Bun.write(OUT, doc)
process.stderr.write(`updated ${OUT}\n`)
