/**
 * Production Workers entry for the ISR demo — the same app, but its page cache lives in **Workers KV**
 * (KVCacheStore), so cached pages and on-demand purges hold ACROSS worker instances (a per-instance
 * MemoryCacheStore can't). `ctx.waitUntil` keeps the worker alive while a stale page regenerates
 * behind the request.
 *
 * Build + run locally on real workerd (miniflare provides a local KV — no Cloudflare account needed):
 *   bun run examples/isr-react/build.ts
 *   (cd examples/isr-react && bunx wrangler dev)
 *
 * The ONLY difference from server.ts is the store: MemoryCacheStore → KVCacheStore(env.ISR_CACHE).
 */
import { inProcessClient } from "@nifrajs/client"
import {
  createWebApp,
  KVCacheStore,
  type KVNamespaceLike,
  revalidateEndpoint,
  withISR,
} from "@nifrajs/web"
import { reactAdapter } from "@nifrajs/web-react"
import { backend } from "./backend"
// Generated by build.ts (buildServer): the static-import route manifest + the baked client entry URL.
// No node:fs / dynamic-path import, so it runs on workerd.
import { clientEntry, manifest } from "./server-manifest"

const app = createWebApp({
  adapter: reactAdapter,
  manifest,
  clientEntry,
  api: inProcessClient(backend),
  title: "nifra — ISR demo (edge)",
})

/** Workers bindings (wrangler.toml → [[kv_namespaces]] + [vars]). */
interface Env {
  /** The ISR page cache (a KV namespace binding). */
  readonly ISR_CACHE: KVNamespaceLike
  /** Shared secret for the on-demand purge endpoint. */
  readonly REVALIDATE_SECRET?: string
}

/** Minimal shape of the Workers execution context — just `waitUntil`. */
interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void
}

export default {
  async fetch(req: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    // KV is the shared, durable store: the page cache + on-demand purges hold across instances. The
    // 1-day GC backstop evicts abandoned entries (it must exceed the longest `revalidate` window so
    // KV expiry never turns a stale-while-revalidate into a blocking miss).
    const store = new KVCacheStore(env.ISR_CACHE, { expirationTtl: 86_400 })

    // On-demand purge (POST). `withISR` would pass a POST straight through anyway, but routing it
    // explicitly here keeps it independent of the app's route table.
    if (new URL(req.url).pathname === "/__nifra/revalidate") {
      return revalidateEndpoint({ store, secret: env.REVALIDATE_SECRET ?? "" })(req)
    }

    const isr = withISR(app, { store, revalidate: 60, now: () => Date.now() })
    // Forward the platform: `waitUntil` lets the background regeneration of a stale page finish after
    // the response is returned; `env` threads the Workers bindings into loaders (`c.env`).
    const platform = { env, waitUntil: (p: Promise<unknown>) => ctx.waitUntil(p) }
    return isr(req, platform)
  },
}
